In [2]:
import pandas as pd
import os
import requests
import urllib.robotparser as rp
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import random as rand
import pandas as pd
import re
import time
from itables import init_notebook_mode
# init_notebook_mode(all_interactive=True)
import numpy as np

c:\Users\gcich\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (2.12.922) or chardet (None)/charset_normalizer (2.1.1) doesn't match a supported version!
  warnings.warn(

In [3]:
extracted_data_output_path = os.path.join(os.getcwd(), '..', 'data', 'data_extracted')
teams_replacement_dict = {
    'Man City': 'Manchester City',
    'Man United': 'Manchester United',
    'Manchester Utd': 'Manchester United',
    'Luton Town': 'Luton',
    'Ipswich Town': 'Ipswich',
    "Nott'm Forest": "Nottingham Forest",
    "Nott'ham Forest": "Nottingham Forest",
    'Leicester City': 'Leicester',
    'Newcastle Utd': 'Newcastle',
    'Sheffield Utd': 'Sheffield United',
    'Stoke City': 'Stoke',
    'Swansea City': 'Swansea',
    'Cardiff City': 'Cardiff',
    'Norwich City': 'Norwich',
    'Leeds United': 'Leeds'
    
}

Read base data from data_co_uk

In [ ]:
cols = [
    'date_time',
    'referee',
    'home_team',
    'away_team',
    'home_goals',
    'away_goals',
    'result',
    'home_goals_h1',
    'away_goals_h1',
    'result_h1',
    'home_shots',
    'away_shots',
    'home_shots_on_target',
    'away_shots_on_target',
    'home_corners',
    'away_corners',
    'home_fouls',
    'away_fouls',
    'home_yellow_cards',
    'away_yellow_cards',
    'home_red_cards',
    'away_red_cards',
    'home_win_odds',
    'draw_odds',
    'away_win_odds',
    'over_2_5_goals_odds',
    'under_2_5_goals_odds'
]
base_data = pd.DataFrame(columns=cols)
data_path = os.path.join(os.getcwd(), '..', 'data', 'data_co_uk')
for filename in os.listdir(data_path):
    if os.path.splitext(filename)[1] != '.csv':
        continue

    data = pd.read_csv(os.path.join(data_path,filename))
    data = data.rename(columns={
        'Referee': 'referee',
        'HomeTeam': 'home_team',
        'AwayTeam': 'away_team',
        'FTHG': 'home_goals',
        'FTAG': 'away_goals',
        'FTR': 'result',
        'HTHG': 'home_goals_h1',
        'HTAG': 'away_goals_h1',
        'HTR': 'result_h1',
        'HS': 'home_shots',
        'AS': 'away_shots',
        'HST': 'home_shots_on_target',
        'AST': 'away_shots_on_target',
        'HC': 'home_corners',
        'AC': 'away_corners',
        'HF': 'home_fouls',
        'AF': 'away_fouls',
        'HY': 'home_yellow_cards',
        'AY': 'away_yellow_cards',
        'HR': 'home_red_cards',
        'AR': 'away_red_cards'
    })
    
    if filename not in ['PL_17_18.csv', 'PL_18_19.csv']:
        data = data.rename(columns={
            'AvgH': 'home_win_odds',
            'AvgD':	'draw_odds',
            'AvgA': 'away_win_odds',
            'Avg>2.5': 'over_2_5_goals_odds',
            'Avg<2.5': 'under_2_5_goals_odds'
        })
    else:
        data = data.rename(columns={
            'BbAv>2.5': 'over_2_5_goals_odds',
            'BbAv<2.5': 'under_2_5_goals_odds'
        })
        data['home_win_odds'] = np.round((data['B365H'] + data['BWH'] + data['IWH'] + data['PSH'] + data['WHH'] + data['VCH'])/ 6,2)
        data['draw_odds'] = np.round((data['B365D'] + data['BWD'] + data['IWD'] + data['PSD'] + data['WHD'] + data['VCD']) / 6,2)
        data['away_win_odds'] = np.round((data['B365A'] + data['BWA'] + data['IWA'] + data['PSA'] + data['WHA'] + data['VCA']) / 6,2)
    
    data['date_time'] = data['Date'] + ' ' + data['Time'] if 'Time' in data.columns else data['Date'] + ' ' + '00:00'
    data = data[cols]
    data['date_time'] = pd.to_datetime(data['date_time'], format='%d/%m/%Y %H:%M')
    base_data = pd.concat([base_data, data], axis=0)

base_data = base_data.replace(to_replace=teams_replacement_dict)
base_data['idx'] = base_data.apply(lambda row: f"{str(row['date_time'])[:10]}_{row['home_team']}_{row['away_team']}", axis=1)

if not os.path.exists(os.path.join(extracted_data_output_path, 'base_data.csv')):
    base_data.to_csv(os.path.join(extracted_data_output_path, 'base_data.csv'), index=False)

C:\Users\gcich\AppData\Local\Temp\ipykernel_14640\2445090583.py:81: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  base_data = pd.concat([base_data, data], axis=0)
C:\Users\gcich\AppData\Local\Temp\ipykernel_14640\2445090583.py:83: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  base_data = base_data.replace(to_replace=teams_replacement_dict)

Scrape xG data

In [7]:
def get_page_html(url):
    response = requests.get(url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3', 'Accept-Language': 'en-US,en;q=0.9'})
    if response.status_code == 200:
        return response.text
    else:
        raise Exception(f'Incorrect status returned: {response.status_code}')
    # else:
    #     raise Exception("This link is not allowed for scraping by robots.txt")
    
def get_elements(page_html, select_phrase):
    """get elements of the website using soup.select method."""
    soup = BeautifulSoup(page_html, 'html.parser')
    return soup.select(select_phrase)

def getPattern(tag_list, pattern, limit, output_datatype = 'int'):
    """searches for given pattern in input_list"""
    output_list = []
    for i in range(limit):
        match = re.search(pattern,tag_list[i].text)
        if match:
            if output_datatype == 'int':
                match = int(match.group())
            elif output_datatype == 'float':
                match = float(match.group())
                
            output_list.append(match)
        else:
            output_list.append(0)
    return output_list

In [ ]:
url_list = [
    'https://fbref.com/en/comps/9/2017-2018/schedule/2017-2018-Premier-League-Scores-and-Fixtures',
    'https://fbref.com/en/comps/9/2018-2019/schedule/2018-2019-Premier-League-Scores-and-Fixtures',
    'https://fbref.com/en/comps/9/2019-2020/schedule/2019-2020-Premier-League-Scores-and-Fixtures',
    'https://fbref.com/en/comps/9/2020-2021/schedule/2020-2021-Premier-League-Scores-and-Fixtures',
    'https://fbref.com/en/comps/9/2021-2022/schedule/2021-2022-Premier-League-Scores-and-Fixtures',
    'https://fbref.com/en/comps/9/2022-2023/schedule/2022-2023-Premier-League-Scores-and-Fixtures',
    'https://fbref.com/en/comps/9/2023-2024/schedule/2023-2024-Premier-League-Scores-and-Fixtures',
    'https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures'
]
html_list = []
for url in url_list:
    html_list.append(get_page_html(url))
    time.sleep(2)

html_list

['    \n      \n<!DOCTYPE html>\n<html data-version="klecko-" data-root="/home/fb/deploy/www/base" lang="en" class="no-js" >\n<head>\n    <meta charset="utf-8">\n    <meta http-equiv="x-ua-compatible" content="ie=edge">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0" />\n    <link rel="dns-prefetch" href="https://cdn.ssref.net/req/202505152" />\n<script>\n/* https://docs.osano.com/hc/en-us/articles/22469433444372-Google-Consent-Mode-v2  */\n  window.dataLayer = window.dataLayer ||[];\n      function gtag(){dataLayer.push(arguments);}\n      gtag(\'consent\',\'default\',{\n        \'ad_storage\':\'denied\',\n        \'analytics_storage\':\'denied\',\n        \'ad_user_data\':\'denied\',\n        \'ad_personalization\':\'denied\',\n        \'personalization_storage\':\'denied\',\n        \'functionality_storage\':\'granted\',\n        \'security_storage\':\'granted\',\n        \'wait_for_update\': 500\n      });\n      gtag("set", "ads_data_redaction", true);\n</script>\n<script src="https://cmp.osano.com/16CGnCU8UtNhM14sg/12669873-8cf8-41e2-be1f-1cb803cbffe0/osano.js"></script>\n<style>.osano-cm-widget{display: none;}</style> \n\n\n\n\n    <title>2021-2022 Premier League Scores & Fixtures | FBref.com</title>\n\n    \n    \n    <meta name="Description" content="Check out Scores & Fixtures for the 2021-2022 Premier League season.">\n    <link rel="canonical" href="https://fbref.com/en/comps/9/2021-2022/schedule/2021-2022-Premier-League-Scores-and-Fixtures" />\n        \n\t<link rel="alternate" href="https://fbref.com/en/comps/9/2021-2022/schedule/2021-2022-Premier-League-Scores-and-Fixtures" hreflang="x-default" />\n\t<link rel="alternate" href="https://fbref.com/pt/comps/9/2021-2022/cronograma/2021-2022-Premier-League-Resultados-e-Calendarios" hreflang="pt-br" />\n\t<link rel="alternate" href="https://fbref.com/pt/comps/9/2021-2022/cronograma/2021-2022-Premier-League-Resultados-e-Calendarios" hreflang="pt-pt" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-fr" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-cd" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-ca" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-cm" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-ci" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-be" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-ma" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-gn" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-dz" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-ht" />\n\t<link rel="alternate" href="https://fbref.com/de/wettbewerbe/9/2021-2022/spielplan/2021-2022-Premier-League-Ergebnisse-and-Spiele" hreflang="de-de" />\n\t<link rel="alternate" href="https://fbref.com/de/wettbewerbe/9/2021-2022/spielplan/2021-2022-Premier-League-Ergebnisse-and-Spiele" hreflang="de-at" />\n\t<link rel="alternate" href="https://fbref.com/de/wettbewerbe/9/2021-2022/spielplan/2021-2022-Premier-League-Ergebnisse-and-Spiele" hreflang="de-ch" />\n\t<link rel="alternate" href="https://fbref.com/en/comps/9/2021-2022/schedule/2021-2022-Premier-League-Scores-and-Fixtures" hreflang="en" />\n\t<link rel="alternate" href="https://fbref.com/it/comp/9/2021-2022/calendario/Punteggi-e-partite-2021-2022-Premier-League" hreflang="it-it" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-es" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-mx" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-co" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-ar" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-cl" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-pe" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-us" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-py" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-ec" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-uy" />\n    \n\n<!-- include:start ="/inc/klecko_header_fb.html_f" -->\n<!-- no:cookie fast load the css.           -->\n<script>function gup(n) {n = n.replace(/[\\[]/, \'\\\\[\').replace(/[\\]]/, \'\\\\]\'); var r = new RegExp(\'[\\\\?&]\'+n+\'=([^&#]*)\'); var re = r.exec(location.search);   return re === null?\'\':decodeURIComponent(re[1].replace(/\\+/g,\' \'));}; document.srdev = gup(\'srdev\')</script>\n<script>if (!document.srdev && (location.hostname === \'sup.fb.srdevel.com\')) { document.srdev = \'aw\'; }/* sf: hardcode this in for sup.fb.srdevel.com for testing purposes. */</script>\n<link rel="preconnect" href="https://cdn.ssref.net" crossorigin>\n<link rel="preload"    href="https://cdn.ssref.net/req/202505152/icons/sr_icons-min.svg?fb" as="fetch" crossorigin>\n<link rel="preload"    href="https://fbref.com/short/inc/main_nav_menu.json" as="fetch" crossorigin>\n<link rel="preload"    href="https://cdn.ssref.net/req/201604190/images/chosen-sprite.png" as="image" crossorigin>\n<link rel="preload"    href="https://cdn.ssref.net/req/202505152/css/fb/sr-min.css" as="style"    crossorigin>\n\n<!-- CSS start -->\n <style>html,body{margin:0;padding:0;font:14px/1.25 "Helvetica Neue",helvetica,arial,sans-serif;color:#000}@media(prefers-reduced-motion:no-preference){html:not(.backstop){scroll-behavior:smooth}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto!important}*{animation:none!important;transition-duration:0s!important}}html:not(.backstop) div,html:not(.backstop) span{scroll-margin:2.5em 0 0 0;scroll-snap-margin:2.5em 0 0 0}body{position:relative;background:#c9cbcd;z-index:0;-webkit-text-size-adjust:none;-moz-text-size-adjust:none;-ms-text-size-adjust:none}a img{border:0}ul,li,ol{margin:0;padding:0;list-style-type:none}table th,table td{border:0}iframe{max-width:100%}code{background:#eee}a,button,input,select,textarea,label,summary{touch-action:manipulation;-ms-touch-action:manipulation}::selection{background:#ff0;text-shadow:none}html.no-js .hasmore,html.no-js .js,html.js .no-js,html.no-js button,html.is_build .hide_build,html.is_dev .hide_dev,html.is_live .hide_live{display:none!important}.js-select{visibility:hidden}a[href]{color:#34d}a[href]:visited{color:#848}a[href]:hover{color:#5e44b3}a[href]:active{color:#b12}a[href^="tel:"]::before{content:"\\260E";display:inline-block;margin-right:0}a[href^="mailto:"]::before{content:"\\2709";display:inline-block;margin-right:0}.icon_group a[href^="tel:"]:before,.icon_group a[href^="mailto:"]:before{content:""}.screen_only{display:initial}.user_logged_in .not_logged_in,.logged_in,.sr_cpi_control,.print_only{display:none}#perflog,#modernizr,.user_logged_in .logged_in{display:block}h2{color:#000;margin-bottom:5px;font-size:1.5em}img.right{float:right;margin:0 0 5px 5px}img.left{float:left;margin:0 15px 15px 0}sup{font-size:.75em;position:relative;top:-0.4em;vertical-align:baseline}#wrap{width:100%;background:#fff;position:relative}#wrap>div,#wrap>ul{width:100%;position:relative;clear:both}.hidden-iso,.hidden,#content .hidden,.gutterad,.more,.print_only,#warnings.hide,#nag_devs{display:none}#inner_nav.hidden{visibility:hidden}.float_wrap{overflow:hidden}.grid2{display:grid;grid-column-gap:10px;grid-template-columns:1fr 1fr}.grid2 img{max-width:100%}.grid2.heavyleft{grid-template-columns:2fr 1fr}.grid2.heavyright{grid-template-columns:1fr 2fr}#header{overflow:visible;background:#edefee;border-bottom:3px solid #026937;min-height:50px}#header img{height:25px;float:left;padding:8px 0 8px 2%;max-width:71%;max-width:calc(95% - 80px)}#header #nav_trigger{display:block;cursor:pointer;float:right;padding:7px 2% 7px 1%;height:30px}#header #nav_trigger a{color:#01371a;font-size:20px;font-weight:bold;text-decoration:none;display:inline-block}#header #nav_trigger a:before{color:#01371a;content:"\\2630 ";font-weight:normal}#header #nav{display:none;clear:both;width:88%;background:#fff;padding:7px 6% 0;border-bottom:3px solid #01371a;border-top:3px solid #01371a;overflow:hidden;font-size:12px}#header #nav .usertools{font-weight:bold;font-size:12px;margin:0 0 4px;padding:7px 6% 0;border-top:1px solid #c9cbcd}#header #nav .breadcrumbs{font-size:12px;padding:7px 6%;border-top:1px solid #c9cbcd}#header #nav_trigger.open{background:#01371a}#header #nav_trigger.open a{color:#fff}#header #nav_trigger.open a:before{color:#fff}#header #nav.open{display:block}#header .social{margin:15px 0;display:none}#header.open_search{margin-bottom:50px}#header #subnav{display:none}#translations{background-color:#ffa;padding:4px 0;text-align:center;display:none}#translations.show{display:block}#translations .closer{top:4px}#translations .langs{display:inline-block}#translations .links{margin:0 35px 0 0}#translations .links>div{display:inline-block}#translations .links .welcome{font-weight:bold}#header .search{margin-top:10px;clear:both;padding:0 2% 6px}#header .search input,#header .search input:active,#header .search input:focus{height:32px;font-size:20px}.search input[type="search"]{padding:4px 5px;border:#747678 1px solid;width:73%;margin-right:2%}.search input[type="search"].prefilled{background-color:#ffa}.search input[type="submit"]{float:right;background:#01371a;color:white;border:1px solid #747678;padding:0;border-radius:5px;height:24px;width:25%;width:calc(25% - 2px)}.search input[type="submit"]:hover{text-decoration:underline}.search input[type="submit"]:active{background-color:#404542}.search .ac-outline{width:73%;margin-right:2%}.search .ac-outline input[type="search"]{width:100%;margin:0}@media screen and (-webkit-min-device-pixel-ratio:0) and (max-width:400px){#header .search input,#header .search input:active,#header .search input:focus{height:32px;font-size:20px}}#wrap>#info{width:96%;margin:0 auto;padding-bottom:10px}#info .opener,#info .opener:active,#inner_nav div .opener{color:#900;font-weight:bold;clear:both;width:100%;text-align:left;padding:10px 0;border:0;background:transparent}#info button#meta_more_button{border:1px solid #c9cbcd;background-color:#edefee;padding:.5em;margin:.5em 0;text-align:center;width:100%;max-width:400px;text-overflow:ellipsis;white-space:nowrap;overflow:hidden;display:none}#info button#meta_more_button.show{display:inline-block}#info #meta>div>p:nth-child(n+6){display:none}#info.open #meta>div>p:nth-child(n+6){display:block}#info #meta .opener{display:none}#info #meta{margin-top:10px;overflow:hidden}#info #meta p{font-size:.93em;margin:3px 0}#info #meta>div.media-item{float:right;margin-left:10px;width:70px}#info #meta>div.media-item.country{width:100px;height:75px}#info #meta>div.media-item.country .flag{width:100%;height:100%;background-size:100%}#info .media-item img{width:100%;height:auto;border:1px solid black;box-sizing:border-box}#info .media-item img.additional{display:none}#info .media-item.logo img,.bbr #info .media-item img,.cbb #info .media-item img{border:0}#info #meta .media-item p{margin:3px 0;font-size:.785em;font-style:italic}#info #meta .media-item.loader p{visibility:hidden}#info h1{margin-top:0;margin-bottom:5px;line-height:1.1em;font-size:1.5em}#info h1+p{margin-top:5px}#info #bling{margin:6px 1% 6px 0;color:#fff;height:24px;overflow:hidden;float:left;width:88%;display:grid;grid-gap:5px 4px;grid-template-columns:repeat(auto-fill,minmax(100px,1fr))}#info.teams #bling{width:100%}#info #bling li{padding:4px 1.25%;text-align:center;position:relative;height:15px;background:#01371a;font-size:.85em;word-spacing:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;border-radius:5px;display:inline-block;width:27%;margin-bottom:5px}#info.teams #bling li{width:45%}#bling li a{color:inherit;position:relative;z-index:1}#info #bling li.bling_hof{background-color:#ffdb1c;color:#000}#info #bling li.bling_all_star{background-color:#c9cbcd;color:#404542}#info #bling li.bling_hof,#info.teams #bling li.bling_all_star,#info.teams #bling li.bling_champ{grid-column-end:span 2}#info #bling li.important{grid-column-end:span 2}#info #bling li.special{background-color:#ffdb1c;color:#000}#info #bling li.all_star{background-color:#c9cbcd;color:#404542}#info.open #bling{height:auto;width:100%;margin-right:0;float:none;overflow:visible}@supports(display:grid){#info #bling li,#info.open #bling li,#info.teams #bling li{width:auto!important;margin-bottom:0!important}}.uni_holder{margin:3px 0;float:none;width:100%;position:relative}#info .uni_holder{float:left}#bling+.uni_holder{width:11%}#info.open #bling+.uni_holder{width:100%;overflow:visible;float:none;margin-bottom:5px}.uni_holder>a{display:inline-block;position:relative;height:auto;width:28px;margin-bottom:3px;margin-right:.3em;text-decoration:none;overflow:hidden}.uni_holder svg{height:28px;width:28px}.uni_holder svg.jersey{height:35px}.uni_holder svg text{font-size:1.8em;font-weight:bold}.uni_holder svg text.string{font-size:1.3em}.uni_holder svg.jersey text{font-size:1.5em}.uni_holder svg.jersey text.string{font-size:.7em}#info #bling+.uni_holder>a{display:none}#info .uni_holder>a.default,#info.open .uni_holder>a,#info #bling+.uni_holder>a.default{display:inline-block}#info .uni_holder .counter{display:none;position:absolute;height:14px;width:18px;border-radius:50%;color:#fff;font-weight:bold;font-size:10px;top:-4px;left:18px;background:black;text-align:center;border:0;padding:4px 0 0;cursor:pointer;text-overflow:inherit}#info .uni_holder .counter:after{content:\'\';padding:0;font-size:0}#info #bling+.uni_holder .counter{display:block}#info.open #bling+.uni_holder .counter{display:none}#info.open #bling+.uni_holder>a{display:inline-block}#info.open .uni_holder>a{display:inline-block;width:33px}#info.open .uni_holder svg{height:33px;width:33px}#info.open .uni_holder svg.jersey{height:41px}.stats_pullout{overflow:hidden;text-align:center;width:96%;margin:0 auto 15px 0;padding-top:6px}.stats_pullout>div{float:left}.stats_pullout>div:first-child{text-align:left}.stats_pullout>div.p2,.stats_pullout>div.p3{display:none}.stats_pullout>div>div{float:left;margin-left:15px}.stats_pullout>div>div.p2{display:none}.stats_pullout>div:first-child>div{margin-left:0}.stats_pullout span,.stats_pullout h4{color:#900;margin:2px 0;font-size:.785714286em;text-align:center}.stats_pullout p{margin:2px 0;font-size:1.1em}.stats_pullout .caption{clear:both;text-align:left}@media screen and (min-width:520px){.stats_pullout>div.p2{display:block}}@media screen and (min-width:600px){.stats_pullout>div{border-left:1px solid #c9cbcd;margin-left:10px}.stats_pullout>div:first-child{border-left:none;margin-left:0}}@media screen and (min-width:736px){.stats_pullout>div.p2{display:none}}@media screen and (min-width:800px){.stats_pullout>div.p2{display:block}.stats_pullout>div>div.p2{display:block}}.opener{cursor:pointer;position:relative;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}.opener:after{content:"\\25BC";font-size:.75em;padding-left:5px;display:inline-block;text-decoration:none}.opener.open:after{content:"\\25B2"}.note .opener{white-space:normal}.toggleable{display:none}.toggleable.open{display:block}tr.toggleable.open{display:table-row}table.toggleable.open{display:table}span.toggleable.open,em.toggleable.open{display:inline}.hoverer{cursor:pointer}.hoverer:after{content:"\\25BC";position:absolute;top:7px;right:0}html.no-touchevents .hoverer:hover:after{content:"\\25B2"}ul.news_stories>li{margin:5px 10px 0 0;float:none}ul.news_stories.more{display:none}ul.news_stories.more.open{display:block}.bullets{padding-left:20px}.bullets>li{margin-left:0;margin-bottom:6px}ul.bullets>li{list-style-type:disc}ol.bullets>li{list-style-type:decimal}.bullets-inline>li{display:inline-block;margin-right:9px;margin-bottom:10px}.bullets-inline>li:after{content:"\\00B7";margin-left:9px}.bullets-inline>li:last-child:after{content:"";margin-left:0}.bullets-inline>li.logged_in{display:none}.user_logged_in .bullets-inline>li.logged_in{display:inline-block}.desc{font-style:italic;font-size:.93em}.hilite{background-color:#ffa}.modified,.modified *{background-color:#f5f5f5}tr.hilite th,tr.hilite td{background-color:#ffa}.callout{margin:10px 0;padding:10px 15px;border:1px solid #aaa;background:#404542;color:#c9cbcd;font-size:1.1em}.callout a{color:#b3beff}.callout a:visited,.callout a:active{color:#a4adff}.callout a:hover,.callout a:visited:hover,.callout a:active:hover{color:#c4cfff}.callout.light{border-color:#747678;background:#eee;color:#404452}.callout.light a{color:#34d}.callout.light a.button,.callout.light a.button:hover{color:white}.callout.light a:hover{color:#5e44b3}.callout.light h3{background-color:transparent}#content>.notables{background-color:#ffa;border:1px dotted #747678;margin:0 auto;padding:6px;text-align:center;width:auto;max-width:500px;font-size:.93em;display:table}.notables li{margin-top:8px}.notables li:first-child{margin-top:0}.note{color:#444;font-size:.92em}.header{font-weight:bold;font-size:1.16em}.pagelog{width:90%;overflow:scroll}.preformatted-desc{width:90%;overflow:auto}.callout.new_stathead_player_highlight{background-image:url(\'https://cdn.ssref.net/req/202301032/images/stathead/stathead-newspaper-texture.jpg\');background-repeat:repeat;background-position:0 25px;background-color:#fff;border:1px solid #7e3e89;text-align:center;padding:10px 20px 0 20px}.callout.new_stathead_player_highlight #powered_by{color:#fff}.new_stathead_player_highlight .callout_logos{display:flex;justify-content:center;align-items:center;font-weight:bold;font-size:.8em;min-width:500px}.callout_logos div{margin:0 20px}.new_stathead_player_highlight .cta{font-size:90%}.new_stathead_player_highlight .button.stathead_button{background-color:#7e3e89;display:none}.new_stathead_player_highlight img{height:30px}.new_stathead_player_highlight_content{background-color:white;border:1px solid black;border-radius:5px;margin:10px;padding:10px}.box .new_stathead_player_highlight{max-width:900px}.new_stathead_player_highlight .new_stathead_player_highlight_content>div:first-child{margin-bottom:.25em}@media screen and (min-width:736px){.callout.new_stathead_player_highlight{display:grid;align-items:center;justify-content:center}.new_stathead_player_highlight .button.stathead_button{display:block}.new_stathead_player_highlight img{width:100%}}@media screen and (max-width:735px){.new_stathead_player_highlight .callout_logos{

In [4]:
def process_div_stats(div, stats_dict):
    stats_string = str(div).replace('<div>', '').replace('</div>', ',')
    stats_list = stats_string.split('\n')[2:-1]
    for stat in stats_list:
        stat_values = stat.split(',')
        stats_dict[f'home_{stat_values[1]}'] = stat_values[0]
        stats_dict[f'away_{stat_values[1]}'] = stat_values[2]
    
    return stats_dict

def process_subpage_stats(subpage):
    tables = get_elements(subpage, 'table')
    stats_dict = dict()

    possesion_tds = tables[2].find_all('tr')[2].find_all('td')
    possesion_values = [td.find('strong').text for td in possesion_tds]

    stats_dict['home_possesion'] = int(possesion_values[0][:-1])
    stats_dict['away_possesion'] = int(possesion_values[1][:-1])

    passes_tds = tables[2].find_all('tr')[4].find_all('td')
    passes_accuracy_values = [td.find('strong').text for td in passes_tds]

    stats_dict['home_passes_acc'] = int(passes_accuracy_values[0][:-1])
    stats_dict['away_passes_acc'] = int(passes_accuracy_values[1][:-1])

    passes_values = [td.find_all('div')[1].find(string=True, recursive=False).split('\xa0—\xa0') for td in passes_tds]
    # stats_dict['home_passes_acc'] = int(passes_accuracy_values[0][:-1])
    stats_dict['home_passes_total'] = passes_values[0][0].split(' of ')[1]
    stats_dict['home_passes_completed'] = passes_values[0][0].split(' of ')[0]
    stats_dict['away_passes_total'] = passes_values[1][1].split(' of ')[1]
    stats_dict['away_passes_completed'] = passes_values[1][1].split(' of ')[0]

    stats_extra = get_elements(subpage, "div#team_stats_extra")[0]

    stats_extra_divs = stats_extra.find_all('div')
    div_1 = stats_extra_divs[0]
    div_2 = stats_extra_divs[16]
    div_3 = stats_extra_divs[32]

    stats_dict = process_div_stats(div_1, stats_dict)
    stats_dict = process_div_stats(div_2, stats_dict)
    stats_dict =process_div_stats(div_3, stats_dict)

    return stats_dict

In [ ]:
detailed_data = pd.DataFrame(
    columns=[
        'season', 'gameweek', 'dayofweek', 'datetime', 
        'team', 'opponent', 'home_game', 'xG', 'xGA',
        'possesion', 'opponent_possesion', 'passes_accuracy', 
        'opponent_passes_accuracy', 'passes_total', 'passes_completed',
        'opponent_passes_total', 'opponent_passes_completed',
        'crosses', 'opponent_crosses', 'touches', 'opponent_touches'
    ])
year = 2017

for html in html_list:
    season = f"{year}/{year+1}"
    
    table_id = f"table#sched_{year}-{year+1}_9_1 tr"
    rows = get_elements(html, table_id)
    
    for row in rows[1:]:
          
        gw = row.find('th').text
        if gw == '':
            continue
        
        cols = row.find_all('td')
        
        content = [col.text for col in cols[:-2]]
        # print(content)
        
        #list have columns: gameweek, dayofweek, datetime, team, opponent, home/away, xG, xGA
        home_row = [season, gw, content[0], f'{content[1]} {content[2]}', content[3], content[7], 1, content[4], content[6]]
        away_row = [season, gw, content[0], f'{content[1]} {content[2]}', content[7], content[3], 0, content[6], content[4]]

        report_tag = cols[-2].find('a')
        report_link = f"https://fbref.com{report_tag.get('href')}"
        
        subpage = get_page_html(report_link)
        sts = process_subpage_stats(subpage)
        home_row.extend([
            sts['home_possesion'],
            sts['away_possesion'],
            sts['home_passes_acc'],
            sts['away_passes_acc'],
            sts['home_passes_total'],
            sts['home_passes_completed'],
            sts['away_passes_total'],
            sts['away_passes_completed'],    
            sts['home_Crosses'],
            sts['away_Crosses'],
            sts['home_Touches'],
            sts['away_Touches']
        ])
        away_row.extend([
            sts['away_possesion'],
            sts['home_possesion'],
            sts['away_passes_acc'],
            sts['home_passes_acc'],
            sts['away_passes_total'],
            sts['away_passes_completed'],  
            sts['home_passes_total'],
            sts['home_passes_completed'],
            sts['away_Crosses'],
            sts['home_Crosses'],
            sts['away_Touches'],
            sts['home_Touches']
        ])
        
        detailed_data.loc[len(detailed_data)] = home_row
        detailed_data.loc[len(detailed_data)] = away_row
        detailed_data['datetime'] = pd.to_datetime(detailed_data['datetime'])
         
        time.sleep(4)
        
    print(f'year {year} completed')
    year += 1
    
detailed_data.index = detailed_data.index + 1
detailed_data = detailed_data.replace(teams_replacement_dict)
detailed_data['idx'] = detailed_data.apply(lambda row: 
    f"{str(row['datetime'])[:10]}_{row['team']}_{row['opponent']}"
    if row['home_game'] == 1 else
    f"{str(row['datetime'])[:10]}_{row['opponent']}_{row['team']}"
    , axis=1)

year 2021 completed
year 2022 completed
year 2023 completed
year 2024 completed

OSError: Cannot save file into a non-existent directory: 'processed_data'

In [ ]:
detailed_data.to_csv(os.path.join(extracted_data_output_path, 'detailed_data.csv'), index=False)
detailed_data

         season gameweek dayofweek            datetime               team  \
1     2021/2022        1       Fri 2021-08-13 20:00:00          Brentford
2     2021/2022        1       Fri 2021-08-13 20:00:00            Arsenal
3     2021/2022        1       Sat 2021-08-14 12:30:00  Manchester United
4     2021/2022        1       Sat 2021-08-14 12:30:00              Leeds
5     2021/2022        1       Sat 2021-08-14 15:00:00            Everton
...         ...      ...       ...                 ...                ...
3036  2024/2025       38       Sun 2025-05-25 16:00:00            Everton
3037  2024/2025       38       Sun 2025-05-25 16:00:00        Bournemouth
3038  2024/2025       38       Sun 2025-05-25 16:00:00          Leicester
3039  2024/2025       38       Sun 2025-05-25 16:00:00          Tottenham
3040  2024/2025       38       Sun 2025-05-25 16:00:00           Brighton

               opponent  home_game   xG  xGA  possesion  ...  \
1               Arsenal          1  1.2  1.3         36  ...
2             Brentford          0  1.3  1.2         64  ...
3                 Leeds          1  1.5  0.5         49  ...
4     Manchester United          0  0.5  1.5         51  ...
5           Southampton          1  2.4  0.8         48  ...
...                 ...        ...  ...  ...        ...  ...
3036          Newcastle          0  1.2  1.2         35  ...
3037          Leicester          1  1.6  0.3         63  ...
3038        Bournemouth          0  0.3  1.6         37  ...
3039           Brighton          1  2.0  2.2         34  ...
3040          Tottenham          0  2.2  2.0         66  ...

      opponent_passes_accuracy  passes_total  passes_completed  \
1                           84           343               217
2                           63           620               522
3                           77           465               363
4                           78           482               372
5                           67           397               271
...                        ...           ...               ...
3036                        85           318               240
3037                        73           547               440
3038                        80           322               234
3039                        86           301               229
3040                        76           592               509

     opponent_passes_total opponent_passes_completed crosses opponent_crosses  \
1                      620                       522       9               22
2                      343                       217      22                9
3                      482                       372      11               14
4                      465                       363      14               11
5                      424                       283      25               22
...                    ...                       ...     ...              ...
3036                   590                       501      11               34
3037                   322                       234      22                8
3038                   547                       440       8               22
3039                   592                       509       5               33
3040                   301                       229      33                5

     touches opponent_touches                                 idx
1        455              742        2021-08-13_Brentford_Arsenal
2        742              455        2021-08-13_Brentford_Arsenal
3        568              584  2021-08-14_Manchester United_Leeds
4        584              568  2021-08-14_Manchester United_Leeds
5        530              539      2021-08-14_Everton_Southampton
...      ...              ...                                 ...
3036     419              682        2025-05-25_Newcastle_Everton
3037     647              439    2025-05-25_Bournemouth_Leicester
3038     439              647    2025-05-25_Bournemouth_Leicester
3039     424              691       2025-05-25_Tottenham_Brighton
3040     691              424       2025-05-25_Tottenham_Brighton

[3040 rows x 22 columns]

Add cups information to the dataset

In [53]:
detailed_data = pd.read_csv(os.path.join(extracted_data_output_path, 'detailed_data.csv'))
detailed_data['comp_before'] = 0
detailed_data['comp_before_name'] = None
detailed_data['comp_before_date'] = None
detailed_data['comp_after'] = 0
detailed_data['comp_after_name'] = None
detailed_data['comp_after_date'] = None

detailed_data

         season  gameweek dayofweek             datetime         team  \
0     2017/2018         1       Fri  2017-08-11 19:45:00      Arsenal
1     2017/2018         1       Fri  2017-08-11 19:45:00    Leicester
2     2017/2018         1       Sat  2017-08-12 12:30:00      Watford
3     2017/2018         1       Sat  2017-08-12 12:30:00    Liverpool
4     2017/2018         1       Sat  2017-08-12 15:00:00      Everton
...         ...       ...       ...                  ...          ...
6075  2024/2025        38       Sun  2025-05-25 16:00:00      Everton
6076  2024/2025        38       Sun  2025-05-25 16:00:00  Bournemouth
6077  2024/2025        38       Sun  2025-05-25 16:00:00    Leicester
6078  2024/2025        38       Sun  2025-05-25 16:00:00    Tottenham
6079  2024/2025        38       Sun  2025-05-25 16:00:00     Brighton

         opponent  home_game   xG  xGA  possesion  ...  opponent_crosses  \
0       Leicester          1  2.5  1.5         68  ...                18
1         Arsenal          0  1.5  2.5         32  ...                20
2       Liverpool          1  2.1  2.6         46  ...                14
3         Watford          0  2.6  2.1         54  ...                16
4           Stoke          1  0.6  0.4         60  ...                27
...           ...        ...  ...  ...        ...  ...               ...
6075    Newcastle          0  1.2  1.2         35  ...                34
6076    Leicester          1  1.6  0.3         63  ...                 8
6077  Bournemouth          0  0.3  1.6         37  ...                22
6078     Brighton          1  2.0  2.2         34  ...                33
6079    Tottenham          0  2.2  2.0         66  ...                 5

      touches  opponent_touches                               idx  \
0         801               427      2017-08-11_Arsenal_Leicester
1         427               801      2017-08-11_Arsenal_Leicester
2         566               639      2017-08-12_Watford_Liverpool
3         639               566      2017-08-12_Watford_Liverpool
4         670               473          2017-08-12_Everton_Stoke
...       ...               ...                               ...
6075      419               682      2025-05-25_Newcastle_Everton
6076      647               439  2025-05-25_Bournemouth_Leicester
6077      439               647  2025-05-25_Bournemouth_Leicester
6078      424               691     2025-05-25_Tottenham_Brighton
6079      691               424     2025-05-25_Tottenham_Brighton

      comp_before  comp_before_name  comp_before_date  comp_after  \
0               0              None              None           0
1               0              None              None           0
2               0              None              None           0
3               0              None              None           0
4               0              None              None           0
...           ...               ...               ...         ...
6075            0              None              None           0
6076            0              None              None           0
6077            0              None              None           0
6078            0              None              None           0
6079            0              None              None           0

      comp_after_name  comp_after_date
0                None             None
1                None             None
2                None             None
3                None             None
4                None             None
...               ...              ...
6075             None             None
6076             None             None
6077             None             None
6078             None             None
6079             None             None

[6080 rows x 28 columns]

In [48]:
league_stats_urls = [
    'https://fbref.com/en/comps/9/2017-2018/2017-2018-Premier-League-Stats',
    'https://fbref.com/en/comps/9/2018-2019/2018-2019-Premier-League-Stats',
    'https://fbref.com/en/comps/9/2019-2020/2019-2020-Premier-League-Stats',
    'https://fbref.com/en/comps/9/2020-2021/2020-2021-Premier-League-Stats',
    'https://fbref.com/en/comps/9/2021-2022/2021-2022-Premier-League-Stats',
    'https://fbref.com/en/comps/9/2022-2023/2022-2023-Premier-League-Stats',
    'https://fbref.com/en/comps/9/2023-2024/2023-2024-Premier-League-Stats',
    'https://fbref.com/en/comps/9/Premier-League-Stats',
]
team_seasons_df = pd.DataFrame(columns=['season', 'team', 'url'])
year = 2017

for league_url in league_stats_urls:
    season = f"{year}/{year+1}"
    season_html = get_page_html(league_url)
    table_id = f"table#results{year}-{year+1}91_overall tr"
    rows = get_elements(season_html, table_id)

    for row in rows[1:]:
        td = row.find('td')
        team_name = td.find('a').text.strip()
        team_season_url = f"https://fbref.com{td.find('a').get('href')}"
        team_seasons_df.loc[len(team_seasons_df)] = [season, team_name, team_season_url]
     
    year += 1    
    time.sleep(4)
    print(f'Season {season} completed')
team_seasons_df = team_seasons_df.replace(to_replace=teams_replacement_dict)
team_seasons_df

Season 2017/2018 completed
Season 2018/2019 completed
Season 2019/2020 completed
Season 2020/2021 completed
Season 2021/2022 completed
Season 2022/2023 completed
Season 2023/2024 completed
Season 2024/2025 completed

        season               team  \
0    2017/2018    Manchester City
1    2017/2018  Manchester United
2    2017/2018          Tottenham
3    2017/2018          Liverpool
4    2017/2018            Chelsea
..         ...                ...
155  2024/2025             Wolves
156  2024/2025          Tottenham
157  2024/2025          Leicester
158  2024/2025            Ipswich
159  2024/2025        Southampton

                                                   url
0    https://fbref.com/en/squads/b8fd03ef/2017-2018...
1    https://fbref.com/en/squads/19538871/2017-2018...
2    https://fbref.com/en/squads/361ca564/2017-2018...
3    https://fbref.com/en/squads/822bd0ba/2017-2018...
4    https://fbref.com/en/squads/cff3d9bb/2017-2018...
..                                                 ...
155  https://fbref.com/en/squads/8cec06e1/Wolverham...
156  https://fbref.com/en/squads/361ca564/Tottenham...
157  https://fbref.com/en/squads/a2d435b3/Leicester...
158  https://fbref.com/en/squads/b74092de/Ipswich-T...
159  https://fbref.com/en/squads/33c895d4/Southampt...

[160 rows x 3 columns]

In [62]:
# for every team, analyze each season season to get cup matches before and after premier league matches 
for idx, row in team_seasons_df.iterrows():

    team = row['team']
    season = row['season']
    url = row['url']
    
    subpage_html = get_page_html(url)
    table_id = f'table#matchlogs_for tr'
    rows = get_elements(subpage_html, table_id)
    gw_no = 0
    previous_comp = None
    previous_comp_date = None
    # rows in that table are matches played by the team in that season
    for row in rows[1:]:
        th = row.find('th')
        comp_date = th.find('a').text.strip()

        tds = row.find_all('td')
        comp_name = tds[1].find('a').text.strip()
        
        round_name = tds[2].find('a').text.strip()

        # if comp_name is any other comp, rows for previous and next gw are updated
        if comp_name != 'Premier League':
            if gw_no > 0 and previous_comp == 'Premier League':
                idx = (detailed_data['team'] == team) & \
                        (detailed_data['season'] == season) & \
                        (detailed_data['gameweek'] == gw_no)
                detailed_data.loc[idx, 'comp_after'] = 1
                detailed_data.loc[idx, 'comp_after_name'] = comp_name
                detailed_data.loc[idx, 'comp_after_date'] = comp_date
                
        # if comp is premier league, check if previous comp was different
        else:
            gw_no = int(round_name.split(' ')[-1])
            if previous_comp != 'Premier League' and previous_comp is not None:
                idx = (detailed_data['team'] == team) & \
                    (detailed_data['season'] == season) & \
                    (detailed_data['gameweek'] == gw_no)
                print(previous_comp, previous_comp_date)   
                detailed_data.loc[idx, 'comp_before'] = 1
                detailed_data.loc[idx, 'comp_before_name'] = previous_comp
                detailed_data.loc[idx, 'comp_before_date'] = previous_comp_date
            
        previous_comp = comp_name
        previous_comp_date = comp_date
    time.sleep(4)

Champions Lg 2017-09-13
EFL Cup 2017-09-20
Champions Lg 2017-09-26
Champions Lg 2017-10-17
EFL Cup 2017-10-24
Champions Lg 2017-11-01
Champions Lg 2017-11-21
Champions Lg 2017-12-06
EFL Cup 2017-12-19
EFL Cup 2018-01-09
FA Cup 2018-01-28
EFL Cup 2018-02-25
Champions Lg 2018-03-07
Champions Lg 2018-04-04
Champions Lg 2018-04-10
Super Cup 2017-08-08
Champions Lg 2017-09-12
EFL Cup 2017-09-20
Champions Lg 2017-09-28
Champions Lg 2017-10-18
EFL Cup 2017-10-24
Champions Lg 2017-10-31
Champions Lg 2017-11-22
Champions Lg 2017-12-05
EFL Cup 2017-12-20
FA Cup 2018-01-05
FA Cup 2018-01-26
Champions Lg 2018-02-21
FA Cup 2018-03-17
FA Cup 2018-04-21
Champions Lg 2017-09-13
EFL Cup 2017-09-19
Champions Lg 2017-09-26
Champions Lg 2017-10-17
EFL Cup 2017-10-25
Champions Lg 2017-11-01
Champions Lg 2017-11-21
Champions Lg 2017-12-06
FA Cup 2018-01-07
FA Cup 2018-01-27
FA Cup 2018-02-07
FA Cup 2018-02-18
FA Cup 2018-02-28
Champions Lg 2018-03-07
FA Cup 2018-03-17
FA Cup 2018-04-21
Champions Lg 2017-08-15
Champions Lg 2017-08-23
Champions Lg 2017-09-13
EFL Cup 2017-09-19
Champions Lg 2017-09-26
Champions Lg 2017-10-17
Champions Lg 2017-11-01
Champions Lg 2017-11-21
Champions Lg 2017-12-06
FA Cup 2018-01-05
FA Cup 2018-01-27
Champions Lg 2018-02-14
Champions Lg 2018-03-06
Champions Lg 2018-04-04
Champions Lg 2018-04-10
Champions Lg 2018-04-24
Champions Lg 2018-05-02
Community Shield 2017-08-06
Champions Lg 2017-09-12
EFL Cup 2017-09-20
Champions Lg 2017-09-27
Champions Lg 2017-10-18
EFL Cup 2017-10-25
Champions Lg 2017-10-31
Champions Lg 2017-11-22
Champions Lg 2017-12-05
EFL Cup 2017-12-20
EFL Cup 2018-01-10
FA Cup 2018-01-17
FA Cup 2018-01-28
Champions Lg 2018-02-20
FA Cup 2018-03-18
FA Cup 2018-04-22
Community Shield 2017-08-06
Europa Lg 2017-09-14
EFL Cup 2017-09-20
Europa Lg 2017-09-28
Europa Lg 2017-10-19
EFL Cup 2017-10-24
Europa Lg 2017-11-02
Europa Lg 2017-11-23
Europa Lg 2017-12-07
EFL Cup 2017-12-19
EFL Cup 2018-01-10
EFL Cup 2018-01-24
EFL Cup 2018-02-25
Europa Lg 2018-03-08
Europa Lg 2018-03-15
Europa Lg 2018-04-05
Europa Lg 2018-04-12
Europa Lg 2018-04-26
Europa Lg 2018-05-03
EFL Cup 2017-08-23
EFL Cup 2017-09-19
FA Cup 2018-01-06
Europa Lg 2017-08-03
Europa Lg 2017-08-17
Europa Lg 2017-08-24
Europa Lg 2017-09-14
EFL Cup 2017-09-20
Europa Lg 2017-09-28
Europa Lg 2017-10-19
EFL Cup 2017-10-25
Europa Lg 2017-11-02
Europa Lg 2017-11-23
Europa Lg 2017-12-07
FA Cup 2018-01-05
EFL Cup 2017-08-22
EFL Cup 2017-09-19
EFL Cup 2017-10-24
EFL Cup 2017-12-19
FA Cup 2018-01-06
FA Cup 2018-01-16
FA Cup 2018-01-27
FA Cup 2018-02-16
FA Cup 2018-03-18
EFL Cup 2017-08-23
FA Cup 2018-01-06
FA Cup 2018-01-28
EFL Cup 2017-08-22
EFL Cup 2017-09-19
EFL Cup 2017-10-24
FA Cup 2018-01-08
EFL Cup 2017-08-22
EFL Cup 2017-09-19
EFL Cup 2017-10-24
EFL Cup 2017-12-20
FA Cup 2018-01-06
FA Cup 2018-01-17
EFL Cup 2017-08-23
EFL Cup 2017-09-19
EFL Cup 2017-10-25
EFL Cup 2017-12-19
FA Cup 2018-01-07
FA Cup 2018-01-16
FA Cup 2018-01-27
EFL Cup 2017-08-22
FA Cup 2018-01-06
FA Cup 2018-01-27
EFL Cup 2017-08-22
EFL Cup 2017-09-19
FA Cup 2018-01-08
FA Cup 2018-01-27
FA Cup 2018-02-17
FA Cup 2018-03-17
EFL Cup 2017-08-23
EFL Cup 2017-09-19
FA Cup 2018-01-06
FA Cup 2018-01-27
FA Cup 2018-02-06
FA Cup 2018-02-17
EFL Cup 2017-08-23
FA Cup 2018-01-06
FA Cup 2018-01-27
FA Cup 2018-02-17
FA Cup 2018-03-18
FA Cup 2018-04-22
EFL Cup 2017-08-22
EFL Cup 2017-09-19
EFL Cup 2017-10-24
FA Cup 2018-01-06
FA Cup 2018-01-17
FA Cup 2018-01-27
FA Cup 2018-02-06
FA Cup 2018-02-17
FA Cup 2018-02-27
FA Cup 2018-03-17
EFL Cup 2017-08-23
EFL Cup 2017-09-19
FA Cup 2018-01-06
EFL Cup 2017-08-22
EFL Cup 2017-09-20
FA Cup 2018-01-06
FA Cup 2018-01-27
FA Cup 2018-02-17
Community Shield 2018-08-05
Champions Lg 2018-09-19
EFL Cup 2018-09-25
Champions Lg 2018-10-02
Champions Lg 2018-10-23
EFL Cup 2018-11-01
Champions Lg 2018-11-07
Champions Lg 2018-11-27
Champions Lg 2018-12-12
EFL Cup 2018-12-18
EFL Cup 2019-01-09
FA Cup 2019-01-26
EFL Cup 2019-02-24
FA Cup 2019-03-16
Champions Lg 2019-04-09
Champions Lg 2019-04-17
Champions Lg 2018-09-18
EFL Cup 2018-09-26
Champions Lg 2018-10-03
Champions Lg 2018-10-24
Champions Lg 2018-11-06
Champions Lg 2018-11-28
Champions Lg 2018-12-11
FA Cup 2019-01-07
Champions Lg 2019-02-19
Champions Lg 2019-03-13
Champions Lg 2019-04-09
Champions Lg 2019-04-17
Champions Lg 2019-05-01
Champions Lg 2019-05-07
Community Shield 2018-08-05
Europa Lg 2018-09-20
EFL Cup 2018-09-26
Europa Lg 2018-10-04
Europa Lg 2018-10-25
EFL Cup 2018-10-31
Europa Lg 2018-11-08
Europa Lg 2018-11-29
Europa Lg 2018-12-13
EFL Cup 2018-12-19
EFL Cup 2019-01-08
FA Cup 2019-01-27
EFL Cup 2019-02-24
Europa Lg 2019-03-07
Europa Lg 2019-03-14
Europa Lg 2019-04-11
Europa Lg 2019-04-18
Europa Lg 2019-05-02
Europa Lg 2019-05-09
Champions Lg 2018-09-18
EFL Cup 2018-09-26
Champions Lg 2018-10-03
Champions Lg 2018-10-24
EFL Cup 2018-10-31
Champions Lg 2018-11-06
Champions Lg 2018-11-28
Champions Lg 2018-12-11
EFL Cup 2018-12-19
EFL Cup 2019-01-08
FA Cup 2019-01-27
Champions Lg 2019-02-13
Champions Lg 2019-03-05
Champions Lg 2019-04-09
Champions Lg 2019-04-17
Champions Lg 2019-04-30
Champions Lg 2019-05-08
Europa Lg 2018-09-20
EFL Cup 2018-09-26
Europa Lg 2018-10-04
Europa Lg 2018-10-25
EFL Cup 2018-10-31
Europa Lg 2018-11-08
Europa Lg 2018-11-29
Europa Lg 2018-12-13
EFL Cup 2018-12-19
FA Cup 2019-01-05
FA Cup 2019-01-25
Europa Lg 2019-02-21
Europa Lg 2019-03-07
Europa Lg 2019-03-14
Europa Lg 2019-04-11
Europa Lg 2019-04-18
Europa Lg 2019-05-02
Europa Lg 2019-05-09
Champions Lg 2018-09-19
EFL Cup 2018-09-25
Champions Lg 2018-10-02
Champions Lg 2018-10-23
Champions Lg 2018-11-07
Champions Lg 2018-11-27
Champions Lg 2018-12-12
FA Cup 2019-01-05
FA Cup 2019-01-25
FA Cup 2019-02-18
Champions Lg 2019-03-06
FA Cup 2019-03-16
Champions Lg 2019-04-10
Champions Lg 2019-04-16
EFL Cup 2018-08-28
EFL Cup 2018-09-25
FA Cup 2019-01-07
FA Cup 2019-01-26
FA Cup 2019-02-05
FA Cup 2019-02-17
FA Cup 2019-03-16
FA Cup 2019-04-07
EFL Cup 2018-08-29
EFL Cup 2018-10-02
FA Cup 2019-01-05
FA Cup 2019-01-26
EFL Cup 2018-08-28
EFL Cup 2018-09-25
EFL Cup 2018-11-27
EFL Cup 2018-12-18
FA Cup 2019-01-06
EFL Cup 2018-08-28
EFL Cup 2018-09-26
EFL Cup 2018-10-31
FA Cup 2019-01-05
FA Cup 2019-01-26
EFL Cup 2018-08-29
EFL Cup 2018-09-26
FA Cup 2019-01-06
FA Cup 2019-01-26
FA Cup 2019-02-15
FA Cup 2019-03-16
FA Cup 2019-04-07
EFL Cup 2018-08-28
EFL Cup 2018-09-25
EFL Cup 2018-10-31
FA Cup 2019-01-05
FA Cup 2019-01-27
FA Cup 2019-02-17
FA Cup 2019-03-16
EFL Cup 2018-08-29
FA Cup 2019-01-05
FA Cup 2019-01-15
FA Cup 2019-01-26
EFL Cup 2018-08-28
EFL Cup 2018-09-25
EFL Cup 2018-10-30
EFL Cup 2018-12-19
FA Cup 2019-01-05
Europa Lg 2018-08-09
Europa Lg 2018-08-16
Europa Lg 2018-08-23
Europa Lg 2018-08-30
EFL Cup 2018-09-25
FA Cup 2019-01-05
FA Cup 2019-01-26
EFL Cup 2018-08-28
EFL Cup 2018-10-02
EFL Cup 2018-11-27
FA Cup 2019-01-05
FA Cup 2019-01-16
EFL Cup 2018-08-28
FA Cup 2019-01-05
FA Cup 2019-01-26
FA Cup 2019-02-06
FA Cup 2019-02-16
FA Cup 2019-03-17
FA Cup 2019-04-06
EFL Cup 2018-08-28
FA Cup 2019-01-05
EFL Cup 2018-08-28
EFL Cup 2018-09-25
EFL Cup 2018-11-01
FA Cup 2019-01-06
EFL Cup 2018-08-28
FA Cup 2019-01-05
Community Shield 2019-08-04
Super Cup 2019-08-14
Champions Lg 2019-09-17
EFL Cup 2019-09-25
Champions Lg 2019-10-02
Champions Lg 2019-10-23
EFL Cup 2019-10-30
Champions Lg 2019-11-05
Champions Lg 2019-11-27
Champions Lg 2019-12-10
EFL Cup 2019-12-17
FA Cup 2020-01-05
FA Cup 2020-01-26
FA Cup 2020-02-04
Champions Lg 2020-02-18
FA Cup 2020-03-03
Champions Lg 2020-03-11
Community Shield 2019-08-04
Champions Lg 2019-09-18
EFL Cup 2019-09-24
Champions Lg 2019-10-01
Champions Lg 2019-10-22
EFL Cup 2019-10-29
Champions Lg 2019-11-06
Champions Lg 2019-11-26
Champions Lg 2019-12-11
EFL Cup 2019-12-18
EFL Cup 2020-01-07
EFL Cup 2020-01-29
FA Cup 2020-03-04
FA Cup 2020-06-28
FA Cup 2020-07-18
Europa Lg 2019-09-19
EFL Cup 2019-09-25
Europa Lg 2019-10-03
Europa Lg 2019-10-24
EFL Cup 2019-10-30
Europa Lg 2019-11-07
Europa Lg 2019-11-28
Europa Lg 2019-12-12
EFL Cup 2019-12-18
EFL Cup 2020-01-07
FA Cup 2020-01-15
EFL Cup 2020-01-29
Europa Lg 2020-02-20
Europa Lg 2020-02-27
FA Cup 2020-03-05
Europa Lg 2020-03-12
FA Cup 2020-06-27
FA Cup 2020-07-19
Super Cup 2019-08-14
Champions Lg 2019-09-17
EFL Cup 2019-09-25
Champions Lg 2019-10-02
Champions Lg 2019-10-23
EFL Cup 2019-10-30
Champions Lg 2019-11-05
Champions Lg 2019-11-27
Champions Lg 2019-12-10
FA Cup 2020-01-05
FA Cup 2020-01-25
Champions Lg 2020-02-25
FA Cup 2020-03-03
FA Cup 2020-06-28
FA Cup 2020-07-19
EFL Cup 2019-08-28
EFL Cup 2019-09-24
EFL Cup 2019-10-29
EFL Cup 2019-12-18
EFL Cup 2020-01-08
EFL Cup 2020-01-28
FA Cup 2020-03-04
FA Cup 2020-06-28
Champions Lg 2019-09-18
EFL Cup 2019-09-24
Champions Lg 2019-10-01
Champions Lg 2019-10-22
Champions Lg 2019-11-06
Champions Lg 2019-11-26
Champions Lg 2019-12-11
FA Cup 2020-01-05
FA Cup 2020-01-14
FA Cup 2020-01-25
FA Cup 2020-02-05
Champions Lg 2020-02-19
FA Cup 2020-03-04
Champions Lg 2020-03-10
Europa Lg 2019-08-08
Europa Lg 2019-08-15
Europa Lg 2019-08-22
Europa Lg 2019-08-29
Europa Lg 2019-09-19
EFL Cup 2019-09-25
Europa Lg 2019-10-03
Europa Lg 2019-10-24
EFL Cup 2019-10-30
Europa Lg 2019-11-07
Europa Lg 2019-11-28
Europa Lg 2019-12-12
FA Cup 2020-01-04
FA Cup 2020-01-15
Europa Lg 2020-02-20
Europa Lg 2020-02-27
Europa Lg 2020-03-12
Europa Lg 2019-09-19
EFL Cup 2019-09-24
Europa Lg 2019-10-03
Europa Lg 2019-10-24
EFL Cup 2019-10-30
Europa Lg 2019-11-06
Europa Lg 2019-11-28
Europa Lg 2019-12-12
FA Cup 2020-01-06
FA Cup 2020-01-27
Europa Lg 2020-02-20
FA Cup 2020-03-02
FA Cup 2020-06-28
FA Cup 2020-07-18
EFL Cup 2019-08-27
EFL Cup 2019-09-25
FA Cup 2020-01-05
FA Cup 2020-01-25
FA Cup 2020-03-03
FA Cup 2020-06-28
EFL Cup 2019-08-28
FA Cup 2020-01-04
FA Cup 2020-01-25
EFL Cup 2019-08-27
EFL Cup 2019-09-24
EFL Cup 2019-10-29
FA Cup 2020-01-04
FA Cup 2020-01-25
FA Cup 2020-02-05
EFL Cup 2019-08-28
EFL Cup 2019-09-24
EFL Cup 2019-10-29
EFL Cup 2019-12-18
FA Cup 2020-01-05
EFL Cup 2019-08-28
FA Cup 2020-01-04
FA Cup 2020-01-14
FA Cup 2020-01-25
FA Cup 2020-02-04
FA Cup 2020-03-03
FA Cup 2020-06-28
EFL Cup 2019-08-27
FA Cup 2020-01-05
EFL Cup 2019-08-27
EFL Cup 2019-09-25
FA Cup 2020-01-04
EFL Cup 2019-08-27
EFL Cup 2019-09-25
FA Cup 2020-01-05
FA Cup 2020-01-25
EFL Cup 2019-08-27
EFL Cup 2019-09-25
EFL Cup 2019-10-30
EFL Cup 2019-12-17
EFL Cup 2020-01-08
EFL Cup 2020-01-28
EFL Cup 2020-03-01
EFL Cup 2019-08-28
EFL Cup 2019-09-25
FA Cup 2020-01-04
FA Cup 2020-01-27
EFL Cup 2019-08-27
EFL Cup 2019-09-24
EFL Cup 2019-10-29
FA Cup 2020-01-04
FA Cup 2020-01-23
EFL Cup 2019-08-27
FA Cup 2020-01-04
FA Cup 2020-01-25
FA Cup 2020-03-04
FA Cup 2020-06-27
EFL Cup 2020-09-24
EFL Cup 2020-09-30
Champions Lg 2020-10-21
Champions Lg 2020-10-27
Champions Lg 2020-11-03
Champions Lg 2020-11-25
Champions Lg 2020-12-01
Champions Lg 2020-12-09
EFL Cup 2020-12-22
FA Cup 2021-01-10
FA Cup 2021-01-23
FA Cup 2021-02-10
Champions Lg 2021-02-24
FA Cup 2021-03-20
Champions Lg 2021-04-06
FA Cup 2021-04-17
Champions Lg 2021-04-28
Champions Lg 2021-05-04
EFL Cup 2020-09-22
EFL Cup 2020-09-30
Champions Lg 2020-10-20
Champions Lg 2020-10-28
Champions Lg 2020-11-04
Champions Lg 2020-11-24
Champions Lg 2020-12-02
Champions Lg 2020-12-08
EFL Cup 2020-12-23
FA Cup 2021-01-09
FA Cup 2021-01-24
FA Cup 2021-02-09
Europa Lg 2021-02-18
Europa Lg 2021-02-25
Europa Lg 2021-03-11
FA Cup 2021-03-21
Europa Lg 2021-04-08
Europa Lg 2021-04-15
Europa Lg 2021-05-06
Community Shield 2020-08-29
EFL Cup 2020-09-24
EFL Cup 2020-10-01
Champions Lg 2020-10-21
Champions Lg 2020-10-27
Champions Lg 2020-11-03
Champions Lg 2020-11-25
Champions Lg 2020-12-01
Champions Lg 2020-12-09
FA Cup 2021-01-08
FA Cup 2021-01-24
Champions Lg 2021-02-16
Champions Lg 2021-03-10
Champions Lg 2021-04-06
Champions Lg 2021-04-14
EFL Cup 2020-09-23
EFL Cup 2020-09-29
Champions Lg 2020-10-20
Champions Lg 2020-10-28
Champions Lg 2020-11-04
Champions Lg 2020-11-24
Champions Lg 2020-12-02
Champions Lg 2020-12-08
FA Cup 2021-01-10
FA Cup 2021-01-24
FA Cup 2021-02-11
Champions Lg 2021-02-23
FA Cup 2021-03-21
Champions Lg 2021-04-07
FA Cup 2021-04-17
Champions Lg 2021-04-27
Champions Lg 2021-05-05
FA Cup 2021-05-15
EFL Cup 2020-09-23
Europa Lg 2020-10-22
Europa Lg 2020-10-29
Europa Lg 2020-11-05
Europa Lg 2020-11-26
Europa Lg 2020-12-03
Europa Lg 2020-12-10
FA Cup 2021-01-09
FA Cup 2021-01-24
FA Cup 2021-02-10
Europa Lg 2021-02-18
Europa Lg 2021-02-25
FA Cup 2021-03-21
FA Cup 2021-04-18
FA Cup 2021-05-15
EFL Cup 2020-09-15
EFL Cup 2020-09-22
EFL Cup 2020-09-30
FA Cup 2021-01-11
FA Cup 2021-01-23
FA Cup 2021-02-09
Europa Lg 2020-09-17
Europa Lg 2020-09-24
Europa Lg 2020-10-01
Europa Lg 2020-10-22
Europa Lg 2020-10-29
Europa Lg 2020-11-05
Europa Lg 2020-11-26
Europa Lg 2020-12-03
Europa Lg 2020-12-10
EFL Cup 2020-12-23
FA Cup 2021-01-10
FA Cup 2021-01-25
FA Cup 2021-02-10
Europa Lg 2021-02-18
Europa Lg 2021-02-24
Europa Lg 2021-03-11
Europa Lg 2021-03-18
EFL Cup 2021-04-25
Community Shield 2020-08-29
EFL Cup 2020-09-23
EFL Cup 2020-10-01
Europa Lg 2020-10-22
Europa Lg 2020-10-29
Europa Lg 2020-11-05
Europa Lg 2020-11-26
Europa Lg 2020-12-03
Europa Lg 2020-12-10
EFL Cup 2020-12-22
FA Cup 2021-01-09
FA Cup 2021-01-23
Europa Lg 2021-02-18
Europa Lg 2021-02-25
Europa Lg 2021-03-11
Europa Lg 2021-03-18
Europa Lg 2021-04-08
Europa Lg 2021-04-15
Europa Lg 2021-04-29
Europa Lg 2021-05-06
EFL Cup 2020-09-16
FA Cup 2021-01-10
EFL Cup 2020-09-16
EFL Cup 2020-09-23
EFL Cup 2020-09-30
EFL Cup 2020-12-23
FA Cup 2021-01-09
FA Cup 2021-01-24
FA Cup 2021-02-10
FA Cup 2021-03-20
EFL Cup 2020-09-15
EFL Cup 2020-09-24
EFL Cup 2020-10-01
FA Cup 2021-01-08
EFL Cup 2020-09-15
EFL Cup 2020-09-23
EFL Cup 2020-09-30
EFL Cup 2020-12-22
FA Cup 2021-01-09
EFL Cup 2020-09-17
FA Cup 2021-01-08
FA Cup 2021-01-22
FA Cup 2021-02-11
EFL Cup 2020-09-15
FA Cup 2021-01-08
EFL Cup 2020-09-16
FA Cup 2021-01-23
FA Cup 2021-02-11
FA Cup 2021-03-20
FA Cup 2021-04-18
EFL Cup 2020-09-17
EFL Cup 2020-09-23
EFL Cup 2020-09-30
FA Cup 2021-01-10
FA Cup 2021-01-23
FA Cup 2021-02-10
EFL Cup 2020-09-17
EFL Cup 2020-09-23
EFL Cup 2020-09-30
FA Cup 2021-01-09
FA Cup 2021-01-24
FA Cup 2021-02-09
EFL Cup 2020-09-16
EFL Cup 2020-09-23
EFL Cup 2020-10-01
FA Cup 2021-01-09
FA Cup 2021-01-24
EFL Cup 2020-09-16
EFL Cup 2020-09-22
FA Cup 2021-01-09
EFL Cup 2020-09-17
FA Cup 2021-01-09
FA Cup 2021-01-23
FA Cup 2021-02-10
FA Cup 2021-03-21
Community Shield 2021-08-07
Champions Lg 2021-09-15
EFL Cup 2021-09-21
Champions Lg 2021-09-28
Champions Lg 2021-10-19
EFL Cup 2021-10-27
Champions Lg 2021-11-03
Champions Lg 2021-11-24
Champions Lg 2021-12-07
FA Cup 2022-01-07
FA Cup 2022-02-05
Champions Lg 2022-02-15
FA Cup 2022-03-01
Champions Lg 2022-03-09
FA Cup 2022-03-20
Champions Lg 2022-04-05
FA Cup 2022-04-16
Champions Lg 2022-04-26
Champions Lg 2022-05-04
Champions Lg 2021-09-15
EFL Cup 2021-09-21
Champions Lg 2021-09-28
Champions Lg 2021-10-19
EFL Cup 2021-10-27
Champions Lg 2021-11-03
Champions Lg 2021-11-24
Champions Lg 2021-12-07
EFL Cup 2021-12-22
EFL Cup 2022-01-13
EFL Cup 2022-01-20
FA Cup 2022-02-06
Champions Lg 2022-02-16
FA Cup 2022-03-02
Champions Lg 2022-03-08
FA Cup 2022-03-20
Champions Lg 2022-04-05
FA Cup 2022-04-16
Champions Lg 2022-04-27
Champions Lg 2022-05-03
FA Cup 2022-05-14
Super Cup 2021-08-11
Champions Lg 2021-09-14
EFL Cup 2021-09-22
Champions Lg 2021-09-29
Champions Lg 2021-10-20
EFL Cup 2021-10-26
Champions Lg 2021-11-02
Champions Lg 2021-11-23
Champions Lg 2021-12-08
EFL Cup 2021-12-22
EFL Cup 2022-01-12
FA Cup 2022-02-05
FA Cup 2022-03-02
FA Cup 2022-03-19
Champions Lg 2022-04-06
FA Cup 2022-04-17
FA Cup 2022-05-14
Conf Lg 2021-08-19
Conf Lg 2021-08-26
Conf Lg 2021-09-16
EFL Cup 2021-09-22
Conf Lg 2021-09-30
Conf Lg 2021-10-21
EFL Cup 2021-10-27
Conf Lg 2021-11-04
Conf Lg 2021-11-25
Conf Lg 2021-12-09
EFL Cup 2021-12-22
EFL Cup 2022-01-12
FA Cup 2022-02-05
FA Cup 2022-03-01
EFL Cup 2021-08-25
EFL Cup 2021-09-22
EFL Cup 2021-10-26
EFL Cup 2021-12-21
EFL Cup 2022-01-20
Champions Lg 2021-09-14
EFL Cup 2021-09-22
Champions Lg 2021-09-29
Champions Lg 2021-10-20
Champions Lg 2021-11-02
Champions Lg 2021-11-23
Champions Lg 2021-12-08
FA Cup 2022-01-10
FA Cup 2022-02-04
Champions Lg 2022-02-23
Champions Lg 2022-03-15
Europa Lg 2021-09-16
EFL Cup 2021-09-22
Europa Lg 2021-09-30
Europa Lg 2021-10-21
EFL Cup 2021-10-27
Europa Lg 2021-11-04
Europa Lg 2021-11-25
Europa Lg 2021-12-09
EFL Cup 2021-12-22
FA Cup 2022-01-09
FA Cup 2022-02-05
FA Cup 2022-03-02
Europa Lg 2022-03-10
Europa Lg 2022-03-17
Europa Lg 2022-04-07
Europa Lg 2022-04-14
Europa Lg 2022-04-28
Europa Lg 2022-05-05
Community Shield 2021-08-07
Europa Lg 2021-09-16
EFL Cup 2021-09-22
Europa Lg 2021-09-30
Europa Lg 2021-10-20
EFL Cup 2021-10-27
Europa Lg 2021-11-04
Europa Lg 2021-11-25
Europa Lg 2021-12-09
EFL Cup 2021-12-22
FA Cup 2022-01-08
FA Cup 2022-02-06
Conf Lg 2022-02-17
Conf Lg 2022-02-24
Conf Lg 2022-03-10
Conf Lg 2022-03-17
Conf Lg 2022-04-07
Conf Lg 2022-04-14
Conf Lg 2022-04-28
Conf Lg 2022-05-05
EFL Cup 2021-08-24
EFL Cup 2021-09-22
EFL Cup 2021-10-27
FA Cup 2022-01-08
FA Cup 2022-02-05
EFL Cup 2021-08-24
EFL Cup 2021-09-22
FA Cup 2022-01-09
FA Cup 2022-02-05
EFL Cup 2021-08-25
FA Cup 2022-01-08
EFL Cup 2021-08-24
FA Cup 2022-01-08
FA Cup 2022-02-05
FA Cup 2022-03-01
FA Cup 2022-03-20
FA Cup 2022-04-17
EFL Cup 2021-08-24
EFL Cup 2021-09-21
EFL Cup 2021-10-27
EFL Cup 2021-12-22
FA Cup 2022-01-08
FA Cup 2022-02-05
EFL Cup 2021-08-24
EFL Cup 2021-09-22
FA Cup 2022-01-10
EFL Cup 2021-08-25
EFL Cup 2021-09-21
EFL Cup 2021-10-26
FA Cup 2022-01-08
FA Cup 2022-02-05
FA Cup 2022-03-02
FA Cup 2022-03-20
EFL Cup 2021-08-24
EFL Cup 2021-09-21
FA Cup 2022-01-08
FA Cup 2022-02-05
FA Cup 2022-03-03
FA Cup 2022-03-20
EFL Cup 2021-08-24
EFL Cup 2021-09-21
EFL Cup 2021-10-26
FA Cup 2022-01-09
EFL Cup 2021-08-25
EFL Cup 2021-09-21
EFL Cup 2021-10-27
FA Cup 2022-01-08
EFL Cup 2021-08-24
EFL Cup 2021-09-21
FA Cup 2022-01-08
EFL Cup 2021-08-24
EFL Cup 2021-09-21
FA Cup 2022-01-09
FA Cup 2022-02-05
FA Cup 2022-03-02
Community Shield 2022-07-30
Champions Lg 2022-09-14
Champions Lg 2022-10-05
Champions Lg 2022-10-11
Champions Lg 2022-10-25
Champions Lg 2022-11-02
EFL Cup 2022-11-09
EFL Cup 2022-12-22
EFL Cup 2023-01-11
FA Cup 2023-01-27
Champions Lg 2023-02-22
FA Cup 2023-02-28
FA Cup 2023-03-18
Champions Lg 2023-04-11
FA Cup 2023-04-22
Champions Lg 2023-05-09
Champions Lg 2023-05-17
Europa Lg 2022-09-08
Europa Lg 2022-10-06
Europa Lg 2022-10-13
Europa Lg 2022-10-20
Europa Lg 2022-10-27
Europa Lg 2022-11-03
EFL Cup 2022-11-09
FA Cup 2023-01-09
FA Cup 2023-01-27
Europa Lg 2023-03-09
Europa Lg 2023-03-16
Europa Lg 2022-09-15
Europa Lg 2022-10-06
Europa Lg 2022-10-13
Europa Lg 2022-10-27
Europa Lg 2022-11-03
EFL Cup 2022-11-10
EFL Cup 2022-12-21
EFL Cup 2023-01-10
EFL Cup 2023-02-01
Europa Lg 2023-02-16
FA Cup 2023-03-01
Europa Lg 2023-03-09
FA Cup 2023-03-19
Europa Lg 2023-04-13
FA Cup 2023-04-23
EFL Cup 2022-08-24
EFL Cup 2022-11-09
EFL Cup 2022-12-20
EFL Cup 2023-01-10
EFL Cup 2023-01-31
EFL Cup 2023-02-26
Community Shield 2022-07-30
Champions Lg 2022-09-13
Champions Lg 2022-10-04
Champions Lg 2022-10-12
Champions Lg 2022-10-26
Champions Lg 2022-11-01
EFL Cup 2022-11-09
EFL Cup 2022-12-22
FA Cup 2023-01-07
FA Cup 2023-01-17
FA Cup 2023-01-29
Champions Lg 2023-02-21
Champions Lg 2023-03-15
EFL Cup 2022-08-24
EFL Cup 2022-11-09
EFL Cup 2022-12-21
FA Cup 2023-01-07
FA Cup 2023-01-29
FA Cup 2023-02-28
FA Cup 2023-03-19
FA Cup 2023-04-23
EFL Cup 2022-08-23
EFL Cup 2022-11-10
FA Cup 2023-01-08
Champions Lg 2022-09-13
Champions Lg 2022-10-04
Champions Lg 2022-10-12
Champions Lg 2022-10-26
Champions Lg 2022-11-01
EFL Cup 2022-11-09
FA Cup 2023-01-07
FA Cup 2023-01-28
Champions Lg 2023-02-14
FA Cup 2023-03-01
Champions Lg 2023-03-08
EFL Cup 2022-08-23
EFL Cup 2022-11-08
FA Cup 2023-01-07
EFL Cup 2022-08-23
FA Cup 2023-01-07
FA Cup 2023-01-28
FA Cup 2023-02-08
FA Cup 2023-02-28
FA Cup 2023-03-19
EFL Cup 2022-08-23
EFL Cup 2022-11-09
FA Cup 2023-01-07
Champions Lg 2022-09-14
Champions Lg 2022-10-05
Champions Lg 2022-10-11

In [67]:
detailed_data['comp_before_date'] = pd.to_datetime(detailed_data['comp_before_date'], errors='coerce')
detailed_data['comp_after_date'] = pd.to_datetime(detailed_data['comp_after_date'], errors='coerce')
detailed_data

         season  gameweek dayofweek             datetime         team  \
0     2017/2018         1       Fri  2017-08-11 19:45:00      Arsenal
1     2017/2018         1       Fri  2017-08-11 19:45:00    Leicester
2     2017/2018         1       Sat  2017-08-12 12:30:00      Watford
3     2017/2018         1       Sat  2017-08-12 12:30:00    Liverpool
4     2017/2018         1       Sat  2017-08-12 15:00:00      Everton
...         ...       ...       ...                  ...          ...
6075  2024/2025        38       Sun  2025-05-25 16:00:00      Everton
6076  2024/2025        38       Sun  2025-05-25 16:00:00  Bournemouth
6077  2024/2025        38       Sun  2025-05-25 16:00:00    Leicester
6078  2024/2025        38       Sun  2025-05-25 16:00:00    Tottenham
6079  2024/2025        38       Sun  2025-05-25 16:00:00     Brighton

         opponent  home_game   xG  xGA  possesion  ...  opponent_crosses  \
0       Leicester          1  2.5  1.5         68  ...                18
1         Arsenal          0  1.5  2.5         32  ...                20
2       Liverpool          1  2.1  2.6         46  ...                14
3         Watford          0  2.6  2.1         54  ...                16
4           Stoke          1  0.6  0.4         60  ...                27
...           ...        ...  ...  ...        ...  ...               ...
6075    Newcastle          0  1.2  1.2         35  ...                34
6076    Leicester          1  1.6  0.3         63  ...                 8
6077  Bournemouth          0  0.3  1.6         37  ...                22
6078     Brighton          1  2.0  2.2         34  ...                33
6079    Tottenham          0  2.2  2.0         66  ...                 5

      touches  opponent_touches                               idx  \
0         801               427      2017-08-11_Arsenal_Leicester
1         427               801      2017-08-11_Arsenal_Leicester
2         566               639      2017-08-12_Watford_Liverpool
3         639               566      2017-08-12_Watford_Liverpool
4         670               473          2017-08-12_Everton_Stoke
...       ...               ...                               ...
6075      419               682      2025-05-25_Newcastle_Everton
6076      647               439  2025-05-25_Bournemouth_Leicester
6077      439               647  2025-05-25_Bournemouth_Leicester
6078      424               691     2025-05-25_Tottenham_Brighton
6079      691               424     2025-05-25_Tottenham_Brighton

      comp_before  comp_before_name  comp_before_date  comp_after  \
0               1  Community Shield        2017-08-06           0
1               0              None               NaT           0
2               0              None               NaT           0
3               0              None               NaT           1
4               1         Europa Lg        2017-08-03           1
...           ...               ...               ...         ...
6075            0              None               NaT           0
6076            0              None               NaT           0
6077            0              None               NaT           0
6078            1         Europa Lg        2025-05-21           0
6079            0              None               NaT           0

      comp_after_name  comp_after_date
0                None              NaT
1                None              NaT
2                None              NaT
3        Champions Lg       2017-08-15
4           Europa Lg       2017-08-17
...               ...              ...
6075             None              NaT
6076             None              NaT
6077             None              NaT
6078             None              NaT
6079             None              NaT

[6080 rows x 28 columns]

In [68]:
detailed_data.to_csv(os.path.join(extracted_data_output_path, 'detailed_data_with_cups.csv'), index=False)

Add manager information to the dataset

In [ ]:
url_list = [
    'https://fbref.com/en/comps/9/2017-2018/schedule/2017-2018-Premier-League-Scores-and-Fixtures',
    'https://fbref.com/en/comps/9/2018-2019/schedule/2018-2019-Premier-League-Scores-and-Fixtures',
    'https://fbref.com/en/comps/9/2019-2020/schedule/2019-2020-Premier-League-Scores-and-Fixtures',
    'https://fbref.com/en/comps/9/2020-2021/schedule/2020-2021-Premier-League-Scores-and-Fixtures',
    'https://fbref.com/en/comps/9/2021-2022/schedule/2021-2022-Premier-League-Scores-and-Fixtures',
    'https://fbref.com/en/comps/9/2022-2023/schedule/2022-2023-Premier-League-Scores-and-Fixtures',
    'https://fbref.com/en/comps/9/2023-2024/schedule/2023-2024-Premier-League-Scores-and-Fixtures',
    'https://fbref.com/en/comps/9/schedule/Premier-League-Scores-and-Fixtures'
]
html_list = []
for url in url_list:
    html_list.append(get_page_html(url))
    time.sleep(2)

html_list

['    \n      \n<!DOCTYPE html>\n<html data-version="klecko-" data-root="/home/fb/deploy/www/base" lang="en" class="no-js" >\n<head>\n    <meta charset="utf-8">\n    <meta http-equiv="x-ua-compatible" content="ie=edge">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0" />\n    <link rel="dns-prefetch" href="https://cdn.ssref.net/req/202505152" />\n<script>\n/* https://docs.osano.com/hc/en-us/articles/22469433444372-Google-Consent-Mode-v2  */\n  window.dataLayer = window.dataLayer ||[];\n      function gtag(){dataLayer.push(arguments);}\n      gtag(\'consent\',\'default\',{\n        \'ad_storage\':\'denied\',\n        \'analytics_storage\':\'denied\',\n        \'ad_user_data\':\'denied\',\n        \'ad_personalization\':\'denied\',\n        \'personalization_storage\':\'denied\',\n        \'functionality_storage\':\'granted\',\n        \'security_storage\':\'granted\',\n        \'wait_for_update\': 500\n      });\n      gtag("set", "ads_data_redaction", true);\n</script>\n<script src="https://cmp.osano.com/16CGnCU8UtNhM14sg/12669873-8cf8-41e2-be1f-1cb803cbffe0/osano.js"></script>\n<style>.osano-cm-widget{display: none;}</style> \n\n\n\n\n    <title>2021-2022 Premier League Scores & Fixtures | FBref.com</title>\n\n    \n    \n    <meta name="Description" content="Check out Scores & Fixtures for the 2021-2022 Premier League season.">\n    <link rel="canonical" href="https://fbref.com/en/comps/9/2021-2022/schedule/2021-2022-Premier-League-Scores-and-Fixtures" />\n        \n\t<link rel="alternate" href="https://fbref.com/en/comps/9/2021-2022/schedule/2021-2022-Premier-League-Scores-and-Fixtures" hreflang="x-default" />\n\t<link rel="alternate" href="https://fbref.com/pt/comps/9/2021-2022/cronograma/2021-2022-Premier-League-Resultados-e-Calendarios" hreflang="pt-br" />\n\t<link rel="alternate" href="https://fbref.com/pt/comps/9/2021-2022/cronograma/2021-2022-Premier-League-Resultados-e-Calendarios" hreflang="pt-pt" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-fr" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-cd" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-ca" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-cm" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-ci" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-be" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-ma" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-gn" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-dz" />\n\t<link rel="alternate" href="https://fbref.com/fr/comps/9/2021-2022/calendrier/Calendrier-et-resultats-2021-2022-Premier-League" hreflang="fr-ht" />\n\t<link rel="alternate" href="https://fbref.com/de/wettbewerbe/9/2021-2022/spielplan/2021-2022-Premier-League-Ergebnisse-and-Spiele" hreflang="de-de" />\n\t<link rel="alternate" href="https://fbref.com/de/wettbewerbe/9/2021-2022/spielplan/2021-2022-Premier-League-Ergebnisse-and-Spiele" hreflang="de-at" />\n\t<link rel="alternate" href="https://fbref.com/de/wettbewerbe/9/2021-2022/spielplan/2021-2022-Premier-League-Ergebnisse-and-Spiele" hreflang="de-ch" />\n\t<link rel="alternate" href="https://fbref.com/en/comps/9/2021-2022/schedule/2021-2022-Premier-League-Scores-and-Fixtures" hreflang="en" />\n\t<link rel="alternate" href="https://fbref.com/it/comp/9/2021-2022/calendario/Punteggi-e-partite-2021-2022-Premier-League" hreflang="it-it" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-es" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-mx" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-co" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-ar" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-cl" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-pe" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-us" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-py" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-ec" />\n\t<link rel="alternate" href="https://fbref.com/es/comps/9/2021-2022/horario/Marcadores-y-partidos-de-2021-2022-Premier-League" hreflang="es-uy" />\n    \n\n<!-- include:start ="/inc/klecko_header_fb.html_f" -->\n<!-- no:cookie fast load the css.           -->\n<script>function gup(n) {n = n.replace(/[\\[]/, \'\\\\[\').replace(/[\\]]/, \'\\\\]\'); var r = new RegExp(\'[\\\\?&]\'+n+\'=([^&#]*)\'); var re = r.exec(location.search);   return re === null?\'\':decodeURIComponent(re[1].replace(/\\+/g,\' \'));}; document.srdev = gup(\'srdev\')</script>\n<script>if (!document.srdev && (location.hostname === \'sup.fb.srdevel.com\')) { document.srdev = \'aw\'; }/* sf: hardcode this in for sup.fb.srdevel.com for testing purposes. */</script>\n<link rel="preconnect" href="https://cdn.ssref.net" crossorigin>\n<link rel="preload"    href="https://cdn.ssref.net/req/202505152/icons/sr_icons-min.svg?fb" as="fetch" crossorigin>\n<link rel="preload"    href="https://fbref.com/short/inc/main_nav_menu.json" as="fetch" crossorigin>\n<link rel="preload"    href="https://cdn.ssref.net/req/201604190/images/chosen-sprite.png" as="image" crossorigin>\n<link rel="preload"    href="https://cdn.ssref.net/req/202505152/css/fb/sr-min.css" as="style"    crossorigin>\n\n<!-- CSS start -->\n <style>html,body{margin:0;padding:0;font:14px/1.25 "Helvetica Neue",helvetica,arial,sans-serif;color:#000}@media(prefers-reduced-motion:no-preference){html:not(.backstop){scroll-behavior:smooth}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto!important}*{animation:none!important;transition-duration:0s!important}}html:not(.backstop) div,html:not(.backstop) span{scroll-margin:2.5em 0 0 0;scroll-snap-margin:2.5em 0 0 0}body{position:relative;background:#c9cbcd;z-index:0;-webkit-text-size-adjust:none;-moz-text-size-adjust:none;-ms-text-size-adjust:none}a img{border:0}ul,li,ol{margin:0;padding:0;list-style-type:none}table th,table td{border:0}iframe{max-width:100%}code{background:#eee}a,button,input,select,textarea,label,summary{touch-action:manipulation;-ms-touch-action:manipulation}::selection{background:#ff0;text-shadow:none}html.no-js .hasmore,html.no-js .js,html.js .no-js,html.no-js button,html.is_build .hide_build,html.is_dev .hide_dev,html.is_live .hide_live{display:none!important}.js-select{visibility:hidden}a[href]{color:#34d}a[href]:visited{color:#848}a[href]:hover{color:#5e44b3}a[href]:active{color:#b12}a[href^="tel:"]::before{content:"\\260E";display:inline-block;margin-right:0}a[href^="mailto:"]::before{content:"\\2709";display:inline-block;margin-right:0}.icon_group a[href^="tel:"]:before,.icon_group a[href^="mailto:"]:before{content:""}.screen_only{display:initial}.user_logged_in .not_logged_in,.logged_in,.sr_cpi_control,.print_only{display:none}#perflog,#modernizr,.user_logged_in .logged_in{display:block}h2{color:#000;margin-bottom:5px;font-size:1.5em}img.right{float:right;margin:0 0 5px 5px}img.left{float:left;margin:0 15px 15px 0}sup{font-size:.75em;position:relative;top:-0.4em;vertical-align:baseline}#wrap{width:100%;background:#fff;position:relative}#wrap>div,#wrap>ul{width:100%;position:relative;clear:both}.hidden-iso,.hidden,#content .hidden,.gutterad,.more,.print_only,#warnings.hide,#nag_devs{display:none}#inner_nav.hidden{visibility:hidden}.float_wrap{overflow:hidden}.grid2{display:grid;grid-column-gap:10px;grid-template-columns:1fr 1fr}.grid2 img{max-width:100%}.grid2.heavyleft{grid-template-columns:2fr 1fr}.grid2.heavyright{grid-template-columns:1fr 2fr}#header{overflow:visible;background:#edefee;border-bottom:3px solid #026937;min-height:50px}#header img{height:25px;float:left;padding:8px 0 8px 2%;max-width:71%;max-width:calc(95% - 80px)}#header #nav_trigger{display:block;cursor:pointer;float:right;padding:7px 2% 7px 1%;height:30px}#header #nav_trigger a{color:#01371a;font-size:20px;font-weight:bold;text-decoration:none;display:inline-block}#header #nav_trigger a:before{color:#01371a;content:"\\2630 ";font-weight:normal}#header #nav{display:none;clear:both;width:88%;background:#fff;padding:7px 6% 0;border-bottom:3px solid #01371a;border-top:3px solid #01371a;overflow:hidden;font-size:12px}#header #nav .usertools{font-weight:bold;font-size:12px;margin:0 0 4px;padding:7px 6% 0;border-top:1px solid #c9cbcd}#header #nav .breadcrumbs{font-size:12px;padding:7px 6%;border-top:1px solid #c9cbcd}#header #nav_trigger.open{background:#01371a}#header #nav_trigger.open a{color:#fff}#header #nav_trigger.open a:before{color:#fff}#header #nav.open{display:block}#header .social{margin:15px 0;display:none}#header.open_search{margin-bottom:50px}#header #subnav{display:none}#translations{background-color:#ffa;padding:4px 0;text-align:center;display:none}#translations.show{display:block}#translations .closer{top:4px}#translations .langs{display:inline-block}#translations .links{margin:0 35px 0 0}#translations .links>div{display:inline-block}#translations .links .welcome{font-weight:bold}#header .search{margin-top:10px;clear:both;padding:0 2% 6px}#header .search input,#header .search input:active,#header .search input:focus{height:32px;font-size:20px}.search input[type="search"]{padding:4px 5px;border:#747678 1px solid;width:73%;margin-right:2%}.search input[type="search"].prefilled{background-color:#ffa}.search input[type="submit"]{float:right;background:#01371a;color:white;border:1px solid #747678;padding:0;border-radius:5px;height:24px;width:25%;width:calc(25% - 2px)}.search input[type="submit"]:hover{text-decoration:underline}.search input[type="submit"]:active{background-color:#404542}.search .ac-outline{width:73%;margin-right:2%}.search .ac-outline input[type="search"]{width:100%;margin:0}@media screen and (-webkit-min-device-pixel-ratio:0) and (max-width:400px){#header .search input,#header .search input:active,#header .search input:focus{height:32px;font-size:20px}}#wrap>#info{width:96%;margin:0 auto;padding-bottom:10px}#info .opener,#info .opener:active,#inner_nav div .opener{color:#900;font-weight:bold;clear:both;width:100%;text-align:left;padding:10px 0;border:0;background:transparent}#info button#meta_more_button{border:1px solid #c9cbcd;background-color:#edefee;padding:.5em;margin:.5em 0;text-align:center;width:100%;max-width:400px;text-overflow:ellipsis;white-space:nowrap;overflow:hidden;display:none}#info button#meta_more_button.show{display:inline-block}#info #meta>div>p:nth-child(n+6){display:none}#info.open #meta>div>p:nth-child(n+6){display:block}#info #meta .opener{display:none}#info #meta{margin-top:10px;overflow:hidden}#info #meta p{font-size:.93em;margin:3px 0}#info #meta>div.media-item{float:right;margin-left:10px;width:70px}#info #meta>div.media-item.country{width:100px;height:75px}#info #meta>div.media-item.country .flag{width:100%;height:100%;background-size:100%}#info .media-item img{width:100%;height:auto;border:1px solid black;box-sizing:border-box}#info .media-item img.additional{display:none}#info .media-item.logo img,.bbr #info .media-item img,.cbb #info .media-item img{border:0}#info #meta .media-item p{margin:3px 0;font-size:.785em;font-style:italic}#info #meta .media-item.loader p{visibility:hidden}#info h1{margin-top:0;margin-bottom:5px;line-height:1.1em;font-size:1.5em}#info h1+p{margin-top:5px}#info #bling{margin:6px 1% 6px 0;color:#fff;height:24px;overflow:hidden;float:left;width:88%;display:grid;grid-gap:5px 4px;grid-template-columns:repeat(auto-fill,minmax(100px,1fr))}#info.teams #bling{width:100%}#info #bling li{padding:4px 1.25%;text-align:center;position:relative;height:15px;background:#01371a;font-size:.85em;word-spacing:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;border-radius:5px;display:inline-block;width:27%;margin-bottom:5px}#info.teams #bling li{width:45%}#bling li a{color:inherit;position:relative;z-index:1}#info #bling li.bling_hof{background-color:#ffdb1c;color:#000}#info #bling li.bling_all_star{background-color:#c9cbcd;color:#404542}#info #bling li.bling_hof,#info.teams #bling li.bling_all_star,#info.teams #bling li.bling_champ{grid-column-end:span 2}#info #bling li.important{grid-column-end:span 2}#info #bling li.special{background-color:#ffdb1c;color:#000}#info #bling li.all_star{background-color:#c9cbcd;color:#404542}#info.open #bling{height:auto;width:100%;margin-right:0;float:none;overflow:visible}@supports(display:grid){#info #bling li,#info.open #bling li,#info.teams #bling li{width:auto!important;margin-bottom:0!important}}.uni_holder{margin:3px 0;float:none;width:100%;position:relative}#info .uni_holder{float:left}#bling+.uni_holder{width:11%}#info.open #bling+.uni_holder{width:100%;overflow:visible;float:none;margin-bottom:5px}.uni_holder>a{display:inline-block;position:relative;height:auto;width:28px;margin-bottom:3px;margin-right:.3em;text-decoration:none;overflow:hidden}.uni_holder svg{height:28px;width:28px}.uni_holder svg.jersey{height:35px}.uni_holder svg text{font-size:1.8em;font-weight:bold}.uni_holder svg text.string{font-size:1.3em}.uni_holder svg.jersey text{font-size:1.5em}.uni_holder svg.jersey text.string{font-size:.7em}#info #bling+.uni_holder>a{display:none}#info .uni_holder>a.default,#info.open .uni_holder>a,#info #bling+.uni_holder>a.default{display:inline-block}#info .uni_holder .counter{display:none;position:absolute;height:14px;width:18px;border-radius:50%;color:#fff;font-weight:bold;font-size:10px;top:-4px;left:18px;background:black;text-align:center;border:0;padding:4px 0 0;cursor:pointer;text-overflow:inherit}#info .uni_holder .counter:after{content:\'\';padding:0;font-size:0}#info #bling+.uni_holder .counter{display:block}#info.open #bling+.uni_holder .counter{display:none}#info.open #bling+.uni_holder>a{display:inline-block}#info.open .uni_holder>a{display:inline-block;width:33px}#info.open .uni_holder svg{height:33px;width:33px}#info.open .uni_holder svg.jersey{height:41px}.stats_pullout{overflow:hidden;text-align:center;width:96%;margin:0 auto 15px 0;padding-top:6px}.stats_pullout>div{float:left}.stats_pullout>div:first-child{text-align:left}.stats_pullout>div.p2,.stats_pullout>div.p3{display:none}.stats_pullout>div>div{float:left;margin-left:15px}.stats_pullout>div>div.p2{display:none}.stats_pullout>div:first-child>div{margin-left:0}.stats_pullout span,.stats_pullout h4{color:#900;margin:2px 0;font-size:.785714286em;text-align:center}.stats_pullout p{margin:2px 0;font-size:1.1em}.stats_pullout .caption{clear:both;text-align:left}@media screen and (min-width:520px){.stats_pullout>div.p2{display:block}}@media screen and (min-width:600px){.stats_pullout>div{border-left:1px solid #c9cbcd;margin-left:10px}.stats_pullout>div:first-child{border-left:none;margin-left:0}}@media screen and (min-width:736px){.stats_pullout>div.p2{display:none}}@media screen and (min-width:800px){.stats_pullout>div.p2{display:block}.stats_pullout>div>div.p2{display:block}}.opener{cursor:pointer;position:relative;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}.opener:after{content:"\\25BC";font-size:.75em;padding-left:5px;display:inline-block;text-decoration:none}.opener.open:after{content:"\\25B2"}.note .opener{white-space:normal}.toggleable{display:none}.toggleable.open{display:block}tr.toggleable.open{display:table-row}table.toggleable.open{display:table}span.toggleable.open,em.toggleable.open{display:inline}.hoverer{cursor:pointer}.hoverer:after{content:"\\25BC";position:absolute;top:7px;right:0}html.no-touchevents .hoverer:hover:after{content:"\\25B2"}ul.news_stories>li{margin:5px 10px 0 0;float:none}ul.news_stories.more{display:none}ul.news_stories.more.open{display:block}.bullets{padding-left:20px}.bullets>li{margin-left:0;margin-bottom:6px}ul.bullets>li{list-style-type:disc}ol.bullets>li{list-style-type:decimal}.bullets-inline>li{display:inline-block;margin-right:9px;margin-bottom:10px}.bullets-inline>li:after{content:"\\00B7";margin-left:9px}.bullets-inline>li:last-child:after{content:"";margin-left:0}.bullets-inline>li.logged_in{display:none}.user_logged_in .bullets-inline>li.logged_in{display:inline-block}.desc{font-style:italic;font-size:.93em}.hilite{background-color:#ffa}.modified,.modified *{background-color:#f5f5f5}tr.hilite th,tr.hilite td{background-color:#ffa}.callout{margin:10px 0;padding:10px 15px;border:1px solid #aaa;background:#404542;color:#c9cbcd;font-size:1.1em}.callout a{color:#b3beff}.callout a:visited,.callout a:active{color:#a4adff}.callout a:hover,.callout a:visited:hover,.callout a:active:hover{color:#c4cfff}.callout.light{border-color:#747678;background:#eee;color:#404452}.callout.light a{color:#34d}.callout.light a.button,.callout.light a.button:hover{color:white}.callout.light a:hover{color:#5e44b3}.callout.light h3{background-color:transparent}#content>.notables{background-color:#ffa;border:1px dotted #747678;margin:0 auto;padding:6px;text-align:center;width:auto;max-width:500px;font-size:.93em;display:table}.notables li{margin-top:8px}.notables li:first-child{margin-top:0}.note{color:#444;font-size:.92em}.header{font-weight:bold;font-size:1.16em}.pagelog{width:90%;overflow:scroll}.preformatted-desc{width:90%;overflow:auto}.callout.new_stathead_player_highlight{background-image:url(\'https://cdn.ssref.net/req/202301032/images/stathead/stathead-newspaper-texture.jpg\');background-repeat:repeat;background-position:0 25px;background-color:#fff;border:1px solid #7e3e89;text-align:center;padding:10px 20px 0 20px}.callout.new_stathead_player_highlight #powered_by{color:#fff}.new_stathead_player_highlight .callout_logos{display:flex;justify-content:center;align-items:center;font-weight:bold;font-size:.8em;min-width:500px}.callout_logos div{margin:0 20px}.new_stathead_player_highlight .cta{font-size:90%}.new_stathead_player_highlight .button.stathead_button{background-color:#7e3e89;display:none}.new_stathead_player_highlight img{height:30px}.new_stathead_player_highlight_content{background-color:white;border:1px solid black;border-radius:5px;margin:10px;padding:10px}.box .new_stathead_player_highlight{max-width:900px}.new_stathead_player_highlight .new_stathead_player_highlight_content>div:first-child{margin-bottom:.25em}@media screen and (min-width:736px){.callout.new_stathead_player_highlight{display:grid;align-items:center;justify-content:center}.new_stathead_player_highlight .button.stathead_button{display:block}.new_stathead_player_highlight img{width:100%}}@media screen and (max-width:735px){.new_stathead_player_highlight .callout_logos{

In [9]:
def process_subpage_manager(subpage):
    div_scorebox = get_elements(subpage, 'div.scorebox')

    stats_dict = dict()

    home_div = div_scorebox[0].find_all('div', recursive=False)[0]

    manager_home_div = home_div.find('div', class_='datapoint')
    manager_home = manager_home_div.find_all(text=True, recursive=False)[0].strip()[2:]
    stats_dict['home_manager'] = manager_home
    
    away_div = div_scorebox[0].find_all('div', recursive=False)[1]

    manager_away_div = away_div.find('div', class_='datapoint')
    manager_away = manager_away_div.find_all(text=True, recursive=False)[0].strip()[2:]
    stats_dict['away_manager'] = manager_away

    return stats_dict

In [10]:

manager_data = pd.DataFrame(
    columns=[
        'season', 'gameweek', 'datetime', 'team', 'opponent', 'home_game', 'manager'
    ])
year = 2021

for html in html_list:
    season = f"{year}/{year+1}"
    
    table_id = f"table#sched_{year}-{year+1}_9_1 tr"
    rows = get_elements(html, table_id)
    i = 0
    for row in rows[1:]:
          
        gw = row.find('th').text
        if gw == '':
            continue
        
        cols = row.find_all('td')
        
        content = [col.text for col in cols[:-2]]
        # print(content)
        
        #list have columns: gameweek, dayofweek, datetime, team, opponent, home/away, xG, xGA
        home_row = [season, gw, f'{content[1]} {content[2]}', content[3], content[7], 1]
        away_row = [season, gw, f'{content[1]} {content[2]}', content[7], content[3], 0]

        report_tag = cols[-2].find('a')
        report_link = f"https://fbref.com{report_tag.get('href')}"
        
        subpage = get_page_html(report_link)
        sts = process_subpage_manager(subpage)
        home_row.extend([
            sts['home_manager'],
        ])
        away_row.extend([
            sts['away_manager'],
        ])
        
        manager_data.loc[len(manager_data)] = home_row
        manager_data.loc[len(manager_data)] = away_row
        
        time.sleep(4)
        
    print(f'year {year} completed')
    year += 1

manager_data['datetime'] = pd.to_datetime(manager_data['datetime']) 
manager_data.index = manager_data.index + 1
manager_data = manager_data.replace(teams_replacement_dict)
manager_data['idx'] = manager_data.apply(lambda row: 
    f"{str(row['datetime'])[:10]}_{row['team']}_{row['opponent']}"
    if row['home_game'] == 1 else
    f"{str(row['datetime'])[:10]}_{row['opponent']}_{row['team']}"
    , axis=1)

manager_data = manager_data[['idx', 'team', 'manager']]

year 2021 completed
year 2022 completed
year 2023 completed
year 2024 completed

In [11]:
manager_data

,idx,team,manager
1,2021-08-13_Brentford_Arsenal,Brentford,Thomas Frank
2,2021-08-13_Brentford_Arsenal,Arsenal,Mikel Arteta
3,2021-08-14_Manchester United_Leeds,Manchester United,Ole Gunnar Solskjær
4,2021-08-14_Manchester United_Leeds,Leeds,Marcelo Bielsa
5,2021-08-14_Everton_Southampton,Everton,Rafael Benítez
...,...,...,...
3036,2025-05-25_Newcastle_Everton,Everton,David Moyes
3037,2025-05-25_Bournemouth_Leicester,Bournemouth,Andoni Iraola
3038,2025-05-25_Bournemouth_Leicester,Leicester,Ruud van Nistelrooy
3039,2025-05-25_Tottenham_Brighton,Tottenham,Ange Postecoglou
3040,2025-05-25_Tottenham_Brighton,Brighton,Fabian Hürzeler

In [21]:
manager_data_1 = pd.read_csv(os.path.join(extracted_data_output_path, 'manager_data_to_2022-02-09.csv'))
manager_data_1 = manager_data_1[manager_data_1['season'] != '2021/2022']
manager_data_1 = manager_data_1.replace(teams_replacement_dict)
manager_data_1['idx'] = manager_data_1.apply(lambda row: 
    f"{str(row['datetime'])[:10]}_{row['team']}_{row['opponent']}"
    if row['home_game'] == 1 else
    f"{str(row['datetime'])[:10]}_{row['opponent']}_{row['team']}"
    , axis=1)
menager_data_complete = pd.concat([manager_data_1[['idx', 'team', 'manager']], manager_data], axis=0, ignore_index=True)
menager_data_complete.to_csv(os.path.join(extracted_data_output_path, 'manager_data.csv'), index=False)
menager_data_complete

                                   idx         team              manager
0         2017-08-11_Arsenal_Leicester      Arsenal        Arsène Wenger
1         2017-08-11_Arsenal_Leicester    Leicester    Craig Shakespeare
2         2017-08-12_Watford_Liverpool      Watford          Marco Silva
3         2017-08-12_Watford_Liverpool    Liverpool         Jürgen Klopp
4             2017-08-12_Everton_Stoke      Everton        Ronald Koeman
...                                ...          ...                  ...
6075      2025-05-25_Newcastle_Everton      Everton          David Moyes
6076  2025-05-25_Bournemouth_Leicester  Bournemouth        Andoni Iraola
6077  2025-05-25_Bournemouth_Leicester    Leicester  Ruud van Nistelrooy
6078     2025-05-25_Tottenham_Brighton    Tottenham     Ange Postecoglou
6079     2025-05-25_Tottenham_Brighton     Brighton      Fabian Hürzeler

[6080 rows x 3 columns]

In [20]:
menager_data_complete = pd.read_csv(os.path.join(extracted_data_output_path, 'manager_data.csv'))
menager_data_complete

                                    idx            team              manager
0     2017-08-11_Arsenal_Leicester City         Arsenal        Arsène Wenger
1     2017-08-11_Arsenal_Leicester City  Leicester City    Craig Shakespeare
2          2017-08-12_Watford_Liverpool         Watford          Marco Silva
3          2017-08-12_Watford_Liverpool       Liverpool         Jürgen Klopp
4         2017-08-12_Everton_Stoke City         Everton        Ronald Koeman
...                                 ...             ...                  ...
6075       2025-05-25_Newcastle_Everton         Everton          David Moyes
6076   2025-05-25_Bournemouth_Leicester     Bournemouth        Andoni Iraola
6077   2025-05-25_Bournemouth_Leicester       Leicester  Ruud van Nistelrooy
6078      2025-05-25_Tottenham_Brighton       Tottenham     Ange Postecoglou
6079      2025-05-25_Tottenham_Brighton        Brighton      Fabian Hürzeler

[6080 rows x 3 columns]